/* GENERATED by webapp/scripts/build-for-device.mjs — DO NOT EDIT. */
#pragma once
#include <stdint.h>

typedef struct {
    const char *url;
    const uint8_t *data;
    unsigned len;
    const char *content_type;
    int gzipped;
} webui_asset_t;

#define WEBUI_ASSET_COUNT 8
extern const webui_asset_t WEBUI_ASSETS[WEBUI_ASSET_COUNT];

/* The app shell, for the site root and the SPA fallback. A path with no extension is a
 * route, not a file, and must serve this. */
#define WEBUI_INDEX_URL "/index.html"
