/* GENERATED by firmware/tools/gen_web_atlas.py — DO NOT EDIT.
 *
 * The firmware's own font atlases, as TypeScript. Copied verbatim so the web
 * renderer cannot disagree with the device about a glyph (NFR-4); see the
 * generator for why this is a conversion and not a second rasteriser.
 *
 * Atlas bit convention: a SET bit is INK. The framebuffer convention is the
 * opposite (a CLEAR bit is black, HW-6) — the inversion lives in the blitter. */

export interface Glyph {
  /** Offset into the face's bits array. */
  off: number;
  w: number;
  h: number;
  advance: number;
  /** Pen-origin to ink-box offset. by is from the BASELINE and negative above it. */
  bx: number;
  by: number;
}

export interface Face {
  firstChar: number;
  /** Non-ASCII glyphs, keyed by codepoint. Empty when the face has none. */
  extra: Map<number, Glyph>;
  px: number;
  ascent: number;
  descent: number;
  lineHeight: number;
  glyphs: Glyph[];
  bits: Uint8Array;
}

const BODY_GLYPHS: Glyph[] = [
  { off: 0, w: 0, h: 0, advance: 6, bx: 0, by: 0 },
  { off: 0, w: 2, h: 14, advance: 6, bx: 2, by: -14 },
  { off: 14, w: 5, h: 5, advance: 9, bx: 2, by: -14 },
  { off: 19, w: 12, h: 14, advance: 13, bx: 0, by: -14 },
  { off: 47, w: 11, h: 19, advance: 13, bx: 1, by: -17 },
  { off: 85, w: 15, h: 14, advance: 20, bx: 2, by: -14 },
  { off: 113, w: 11, h: 14, advance: 13, bx: 1, by: -14 },
  { off: 141, w: 2, h: 5, advance: 6, bx: 2, by: -14 },
  { off: 146, w: 4, h: 18, advance: 7, bx: 2, by: -15 },
  { off: 164, w: 4, h: 18, advance: 7, bx: 1, by: -15 },
  { off: 182, w: 8, h: 8, advance: 10, bx: 1, by: -14 },
  { off: 190, w: 9, h: 9, advance: 13, bx: 2, by: -10 },
  { off: 208, w: 3, h: 6, advance: 6, bx: 1, by: -2 },
  { off: 214, w: 7, h: 2, advance: 9, bx: 1, by: -7 },
  { off: 216, w: 2, h: 3, advance: 6, bx: 2, by: -3 },
  { off: 219, w: 5, h: 17, advance: 7, bx: 1, by: -15 },
  { off: 236, w: 10, h: 14, advance: 13, bx: 1, by: -14 },
  { off: 264, w: 5, h: 14, advance: 8, bx: 1, by: -14 },
  { off: 278, w: 10, h: 14, advance: 12, bx: 1, by: -14 },
  { off: 306, w: 10, h: 14, advance: 12, bx: 1, by: -14 },
  { off: 334, w: 11, h: 14, advance: 13, bx: 1, by: -14 },
  { off: 362, w: 10, h: 14, advance: 12, bx: 1, by: -14 },
  { off: 390, w: 10, h: 14, advance: 12, bx: 1, by: -14 },
  { off: 418, w: 9, h: 14, advance: 11, bx: 1, by: -14 },
  { off: 446, w: 10, h: 14, advance: 12, bx: 1, by: -14 },
  { off: 474, w: 10, h: 14, advance: 12, bx: 1, by: -14 },
  { off: 502, w: 2, h: 11, advance: 6, bx: 2, by: -11 },
  { off: 513, w: 3, h: 15, advance: 6, bx: 1, by: -11 },
  { off: 528, w: 9, h: 10, advance: 13, bx: 2, by: -11 },
  { off: 548, w: 9, h: 6, advance: 13, bx: 2, by: -9 },
  { off: 560, w: 10, h: 10, advance: 13, bx: 2, by: -11 },
  { off: 580, w: 8, h: 14, advance: 10, bx: 1, by: -14 },
  { off: 594, w: 17, h: 18, advance: 19, bx: 1, by: -14 },
  { off: 648, w: 12, h: 14, advance: 14, bx: 1, by: -14 },
  { off: 676, w: 10, h: 14, advance: 13, bx: 2, by: -14 },
  { off: 704, w: 12, h: 14, advance: 15, bx: 1, by: -14 },
  { off: 732, w: 11, h: 14, advance: 14, bx: 2, by: -14 },
  { off: 760, w: 9, h: 14, advance: 12, bx: 2, by: -14 },
  { off: 788, w: 9, h: 14, advance: 12, bx: 2, by: -14 },
  { off: 816, w: 13, h: 14, advance: 15, bx: 1, by: -14 },
  { off: 844, w: 11, h: 14, advance: 15, bx: 2, by: -14 },
  { off: 872, w: 2, h: 14, advance: 5, bx: 2, by: -14 },
  { off: 886, w: 9, h: 14, advance: 11, bx: 1, by: -14 },
  { off: 914, w: 10, h: 14, advance: 13, bx: 2, by: -14 },
  { off: 942, w: 8, h: 14, advance: 11, bx: 2, by: -14 },
  { off: 956, w: 14, h: 14, advance: 18, bx: 2, by: -14 },
  { off: 984, w: 11, h: 14, advance: 15, bx: 2, by: -14 },
  { off: 1012, w: 13, h: 14, advance: 15, bx: 1, by: -14 },
  { off: 1040, w: 10, h: 14, advance: 13, bx: 2, by: -14 },
  { off: 1068, w: 13, h: 15, advance: 15, bx: 1, by: -14 },
  { off: 1098, w: 10, h: 14, advance: 13, bx: 2, by: -14 },
  { off: 1126, w: 11, h: 14, advance: 13, bx: 1, by: -14 },
  { off: 1154, w: 11, h: 14, advance: 13, bx: 1, by: -14 },
  { off: 1182, w: 11, h: 14, advance: 15, bx: 2, by: -14 },
  { off: 1210, w: 12, h: 14, advance: 14, bx: 1, by: -14 },
  { off: 1238, w: 18, h: 14, advance: 20, bx: 1, by: -14 },
  { off: 1280, w: 12, h: 14, advance: 14, bx: 1, by: -14 },
  { off: 1308, w: 12, h: 14, advance: 14, bx: 1, by: -14 },
  { off: 1336, w: 10, h: 14, advance: 13, bx: 1, by: -14 },
  { off: 1364, w: 4, h: 18, advance: 7, bx: 2, by: -15 },
  { off: 1382, w: 6, h: 18, advance: 7, bx: 1, by: -16 },
  { off: 1400, w: 4, h: 18, advance: 7, bx: 1, by: -15 },
  { off: 1418, w: 7, h: 6, advance: 9, bx: 1, by: -14 },
  { off: 1424, w: 9, h: 2, advance: 9, bx: 0, by: 0 },
  { off: 1428, w: 3, h: 3, advance: 6, bx: 2, by: -15 },
  { off: 1431, w: 9, h: 11, advance: 11, bx: 1, by: -11 },
  { off: 1453, w: 9, h: 14, advance: 12, bx: 2, by: -14 },
  { off: 1481, w: 9, h: 11, advance: 11, bx: 1, by: -11 },
  { off: 1503, w: 10, h: 14, advance: 12, bx: 1, by: -14 },
  { off: 1531, w: 10, h: 11, advance: 12, bx: 1, by: -11 },
  { off: 1553, w: 7, h: 14, advance: 7, bx: 0, by: -14 },
  { off: 1567, w: 10, h: 15, advance: 12, bx: 1, by: -11 },
  { off: 1597, w: 8, h: 14, advance: 12, bx: 2, by: -14 },
  { off: 1611, w: 2, h: 15, advance: 5, bx: 1, by: -15 },
  { off: 1626, w: 3, h: 19, advance: 5, bx: 0, by: -15 },
  { off: 1645, w: 8, h: 14, advance: 11, bx: 2, by: -14 },
  { off: 1659, w: 1, h: 14, advance: 5, bx: 2, by: -14 },
  { off: 1673, w: 14, h: 11, advance: 18, bx: 2, by: -11 },
  { off: 1695, w: 8, h: 11, advance: 12, bx: 2, by: -11 },
  { off: 1706, w: 10, h: 11, advance: 12, bx: 1, by: -11 },
  { off: 1728, w: 9, h: 15, advance: 12, bx: 2, by: -11 },
  { off: 1758, w: 10, h: 15, advance: 12, bx: 1, by: -11 },
  { off: 1788, w: 5, h: 11, advance: 8, bx: 2, by: -11 },
  { off: 1799, w: 8, h: 11, advance: 11, bx: 1, by: -11 },
  { off: 1810, w: 6, h: 14, advance: 7, bx: 0, by: -14 },
  { off: 1824, w: 8, h: 11, advance: 12, bx: 2, by: -11 },
  { off: 1835, w: 10, h: 11, advance: 11, bx: 1, by: -11 },
  { off: 1857, w: 15, h: 11, advance: 16, bx: 1, by: -11 },
  { off: 1879, w: 9, h: 11, advance: 11, bx: 1, by: -11 },
  { off: 1901, w: 10, h: 15, advance: 11, bx: 1, by: -11 },
  { off: 1931, w: 9, h: 11, advance: 11, bx: 1, by: -11 },
  { off: 1953, w: 6, h: 18, advance: 9, bx: 1, by: -14 },
  { off: 1971, w: 1, h: 24, advance: 7, bx: 3, by: -19 },
  { off: 1995, w: 6, h: 18, advance: 9, bx: 1, by: -14 },
  { off: 2013, w: 10, h: 4, advance: 13, bx: 2, by: -8 },
];

/* 2028 bytes of packed 20px glyph data. */
const BODY_B64 =
  'wMDAwMDAwMDAwADAwMDY2NjIyAxgCEAIQH/wP/AYwBjAEIB/4P/gMIAxgDGAIYAEAAQABAAfAH/AZMBEQGQAdAA+AA+ABMAE' +
  'YMRg5MB/wD8ABAAEAHgIfBjMMMxgfEB4wAGAARwDPgYiDCIIIhg+MBweAD8AYwBjAGMANgAcADwAZmDDYMPAwcB/wD5gwMDA' +
  'wMAwMGBgYEDAwMDAwMDAYGBgMDDAQGBgIDAwMDAwMDAwMGBgQMAYGP88PP8YGAgACAAIAP+A/4AIAAgACAAIAGBgQEDAwHz+' +
  'wMDACAgYGBAQMDAgYGBgQMDAgIAeAD+AYYBgwMDAwEDAQMBAwEDAwGDAYYA/gB4AOHjoiAgICAgICAgICAgeAD+AYYBAgACA' +
  'AYABgAMABgAMABgAMAB/gP/AHwB/gGGAAMABgA8ADwABgADAAMDAwGDAf4AfAAOAA4AHgA2ACYAZgDGAIYBhgP/A/+ABgAGA' +
  'AYB/gH+AYABgAGQAfwBjgAGAAMAAwMCAYYB/AB4AHwA/gGDAYABEAN+A8YDgwMDAwMBgwGHAP4AfAP+A/4ABgAMAAwAGAAYA' +
  'DAAMABgAGAAwADAAYAAfAH+AYYBgwGGAPwA/AGGAwMDAwMDAYMB/gB8AHgB/gGGAwMDAwMDAYcA/wAjAAMDAwGGAfwAeAMDA' +
  'wAAAAAAAwMDAYGBgAAAAAAAAYGBAQMDAAIADgA8APADwAMAAcAAcAAeAAYD/gH+AAAAAAH+A/4CAAOAAeAAOAAOAAcAHABwA' +
  'cADAADx/w4MDBw4YGAAAEDgYA/AAD/wAOAYAMAMAYJEAY/mAxjmAxBiAzBiAzBiAxBmAxjmAR/8AY84AMAAAOAAAD/gAA/AA' +
  'BgAPAA8AGQAZgBmAMIAwwD/Af+BgYMBgwDDAMP4A/4DBgMCAwYDBgP8A/4DBwMDAwMDAwP+A/wAPgB/gMHBgMEAAwADAAMAA' +
  'wABAAGAwMHA/4A+A/gD/gMDAwGDAYMBgwGDAYMBgwGDA4MHA/4D+AP+A/wDAAMAAwADAAP8A/wDAAMAAwADAAP8A/4D/gP8A' +
  'wADAAMAAwAD/AP8AwADAAMAAwADAAMAAD4A/4DBwYDBAAMAAwfDB+MAYQBBgMDBwP+APgMBgwGDAYMBgwGDAYP/g/+DAYMBg' +
  'wGDAYMBgwGDAwMDAwMDAwMDAwMDAwAGAAYABgAGAAYABgAGAAYABgMGAwYDDAH8APgDAwMGAwwDHAM4A3AD4APwA5gDGAMMA' +
  'wYDAwMDAwMDAwMDAwMDAwMDA///gHOAc4BzwPPA82GzYbMhszMzMzMaMx4zDDMMMwGDgYPBg8GDYYNxgzGDGYMdgw2DB4MHg' +
  'wODAYA+AH+AwcGAwQBjAGMAYwBjAGEAYYDAwcD/gD4D+AP+AwYDAwMDAwMDBgP8A/ADAAMAAwADAAMAAD4Af4DBwYDBAGMAY' +
  'wBjAGMAYQBhhsDDwP+AP4AAw/gD/gMGAwMDAwMDAwYD/AP4AwwDDAMGAwYDAwB8AP8BgwEBAYABwAD4AB4AAwABgwGDgwH/A' +
  'HwD/4P/gBAAEAAQABAAEAAQABAAEAAQABAAEAAQAwGDAYMBgwGDAYMBgwGDAYMBgwGDAYODAf8AfAMAwwDDAYGBgYGAgwDDA' +
  'MIAZgBmACQAPAA8ABgDAwMDBwMDB4IBB4YBhYYBjIYBjMQAiMwA2MwA2EgA2GgAcHgAcDgAcDADAYGBgMMAxgBmADwAOAA4A' +
  'DwAZgDHAcMBgYMAwwDDgYGDAMMAxgBmADwAOAAYABgAGAAYABgAGAP/Af8ABgAGAAwAGAAYADAAYABgAMABgAP/A/8Dw8MDA' +
  'wMDAwMDAwMDAwMDA8PCAgMDAQEBgYCAgMDAQGBgYCAzwcDAwMDAwMDAwMDAwMDAwcPA4OCxkRsL/gP+AwMBgPgB/AMEAAYAH' +
  'gH+A4YDBgMOA/4A9gIAAgACAAJ4A/wDDgMGAgYCBgIGAwYDDgP8AngAeAH+AYYDAAMAAwADAAMAAYYB/gB4AAMAAwADAHMB/' +
  'wGHAwMDAwMDAwMDAwGHAf8AcwB4AfwBhgMCA/8D/wMAAwABhgH+AHgAePDD+fDAwMDAwMDAwMB7Af8BhwMDAwMDAwMDAwMBh' +
  'wH/AHsAAwEGAf4A/AICAgJ7/w4OBgYGBgYGBwMAAAEBAQEBAQEBAQEBAYGAAACAgICAgICAgICAgIGDgwICAgIOGjJjw8NiM' +
  'joeDgICAgICAgICAgICAgICccP74wwyDDIMMgwyDDIMMgwyDDIMMnv/Dg4GBgYGBgYEeAH+AYYDAwMDAwMDAwMDAYYB/gB4A' +
  'ngD/AMOAwYCBgIGAgYDBgMOA/wCeAIAAgACAAIAAHsB/wGHAwMDAwMDAwMDAwGHAf8AewADAAMAAwADAmPjAgICAgICAgIA+' +
  'f8PAcD4DAcN/PiAwMPx4MDAwMDAwMDwcgYGBgYGBg4PD/3nAwMGAwYBhAGMAIwA2ADYAHAAcAAwAwwbDjMOMZoxmiGTYJNg8' +
  'UDhwGHAYcMGAYwAiADYAHAAcABwANgBjAGMAwYDAwMGAwYBhAGMAIwA2ADYAHAAcAAwACAAYAHAAYAD/gH8AAwAGAAwAHAAY' +
  'ADAAYAD/AP+ADBwQEBAQEDBg4DAwEBAQEBwMgICAgICAgICAgICAgICAgICAgICAgICA4OAwMDAwMDAcDBgwMDAwMPDgIAD4' +
  'wM+AhwAQfEbGxnw4';

const VALUE_GLYPHS: Glyph[] = [
  { off: 0, w: 0, h: 0, advance: 16, bx: 0, by: 0 },
  { off: 0, w: 10, h: 47, advance: 21, bx: 5, by: -47 },
  { off: 94, w: 21, h: 19, advance: 33, bx: 6, by: -47 },
  { off: 151, w: 39, h: 47, advance: 41, bx: 1, by: -47 },
  { off: 386, w: 36, h: 60, advance: 42, bx: 3, by: -54 },
  { off: 686, w: 52, h: 48, advance: 64, bx: 6, by: -47 },
  { off: 1022, w: 38, h: 47, advance: 42, bx: 3, by: -47 },
  { off: 1257, w: 8, h: 19, advance: 21, bx: 6, by: -47 },
  { off: 1276, w: 15, h: 59, advance: 24, bx: 6, by: -50 },
  { off: 1394, w: 15, h: 59, advance: 24, bx: 3, by: -50 },
  { off: 1512, w: 25, h: 27, advance: 35, bx: 5, by: -47 },
  { off: 1620, w: 31, h: 32, advance: 43, bx: 6, by: -35 },
  { off: 1748, w: 11, h: 19, advance: 20, bx: 4, by: -7 },
  { off: 1786, w: 21, h: 7, advance: 30, bx: 4, by: -23 },
  { off: 1807, w: 10, h: 9, advance: 20, bx: 5, by: -9 },
  { off: 1825, w: 22, h: 57, advance: 24, bx: 1, by: -50 },
  { off: 1996, w: 36, h: 47, advance: 42, bx: 3, by: -47 },
  { off: 2231, w: 19, h: 47, advance: 27, bx: 3, by: -47 },
  { off: 2372, w: 32, h: 47, advance: 40, bx: 4, by: -47 },
  { off: 2560, w: 34, h: 47, advance: 41, bx: 3, by: -47 },
  { off: 2795, w: 37, h: 47, advance: 43, bx: 3, by: -47 },
  { off: 3030, w: 33, h: 47, advance: 39, bx: 3, by: -47 },
  { off: 3265, w: 35, h: 47, advance: 41, bx: 3, by: -47 },
  { off: 3500, w: 31, h: 47, advance: 37, bx: 3, by: -47 },
  { off: 3688, w: 35, h: 47, advance: 41, bx: 3, by: -47 },
  { off: 3923, w: 35, h: 47, advance: 41, bx: 3, by: -47 },
  { off: 4158, w: 10, h: 33, advance: 20, bx: 5, by: -33 },
  { off: 4224, w: 12, h: 45, advance: 21, bx: 4, by: -33 },
  { off: 4314, w: 31, h: 35, advance: 43, bx: 5, by: -36 },
  { off: 4454, w: 31, h: 22, advance: 43, bx: 6, by: -30 },
  { off: 4542, w: 31, h: 35, advance: 43, bx: 7, by: -36 },
  { off: 4682, w: 29, h: 47, advance: 35, bx: 3, by: -47 },
  { off: 4870, w: 58, h: 60, advance: 64, bx: 3, by: -47 },
  { off: 5350, w: 43, h: 47, advance: 47, bx: 2, by: -47 },
  { off: 5632, w: 34, h: 47, advance: 42, bx: 5, by: -47 },
  { off: 5867, w: 41, h: 47, advance: 47, bx: 3, by: -47 },
  { off: 6149, w: 38, h: 47, advance: 46, bx: 5, by: -47 },
  { off: 6384, w: 30, h: 47, advance: 39, bx: 5, by: -47 },
  { off: 6572, w: 30, h: 47, advance: 38, bx: 5, by: -47 },
  { off: 6760, w: 42, h: 47, advance: 48, bx: 3, by: -47 },
  { off: 7042, w: 38, h: 47, advance: 48, bx: 5, by: -47 },
  { off: 7277, w: 8, h: 47, advance: 18, bx: 5, by: -47 },
  { off: 7324, w: 30, h: 47, advance: 37, bx: 2, by: -47 },
  { off: 7512, w: 38, h: 47, advance: 45, bx: 5, by: -47 },
  { off: 7747, w: 29, h: 47, advance: 36, bx: 5, by: -47 },
  { off: 7935, w: 49, h: 47, advance: 59, bx: 5, by: -47 },
  { off: 8264, w: 39, h: 47, advance: 49, bx: 5, by: -47 },
  { off: 8499, w: 43, h: 47, advance: 49, bx: 3, by: -47 },
  { off: 8781, w: 33, h: 47, advance: 41, bx: 5, by: -47 },
  { off: 9016, w: 43, h: 51, advance: 49, bx: 3, by: -47 },
  { off: 9322, w: 35, h: 47, advance: 42, bx: 5, by: -47 },
  { off: 9557, w: 36, h: 48, advance: 42, bx: 3, by: -47 },
  { off: 9797, w: 37, h: 47, advance: 42, bx: 3, by: -47 },
  { off: 10032, w: 37, h: 47, advance: 47, bx: 5, by: -47 },
  { off: 10267, w: 43, h: 47, advance: 47, bx: 2, by: -47 },
  { off: 10549, w: 62, h: 47, advance: 65, bx: 2, by: -47 },
  { off: 10925, w: 42, h: 47, advance: 46, bx: 2, by: -47 },
  { off: 11207, w: 42, h: 47, advance: 46, bx: 2, by: -47 },
  { off: 11489, w: 34, h: 47, advance: 42, bx: 4, by: -47 },
  { off: 11724, w: 14, h: 59, advance: 24, bx: 6, by: -50 },
  { off: 11842, w: 22, h: 57, advance: 24, bx: 1, by: -50 },
  { off: 12013, w: 15, h: 59, advance: 24, bx: 3, by: -50 },
  { off: 12131, w: 25, h: 21, advance: 31, bx: 3, by: -47 },
  { off: 12215, w: 30, h: 7, advance: 30, bx: 0, by: 0 },
  { off: 12243, w: 12, h: 10, advance: 22, bx: 5, by: -50 },
  { off: 12263, w: 30, h: 37, advance: 37, bx: 2, by: -36 },
  { off: 12411, w: 33, h: 47, advance: 40, bx: 4, by: -47 },
  { off: 12646, w: 31, h: 37, advance: 37, bx: 3, by: -36 },
  { off: 12794, w: 33, h: 47, advance: 40, bx: 3, by: -47 },
  { off: 13029, w: 32, h: 37, advance: 38, bx: 3, by: -36 },
  { off: 13177, w: 23, h: 50, advance: 25, bx: 1, by: -50 },
  { off: 13327, w: 33, h: 49, advance: 40, bx: 3, by: -36 },
  { off: 13572, w: 31, h: 47, advance: 39, bx: 4, by: -47 },
  { off: 13760, w: 9, h: 50, advance: 17, bx: 4, by: -50 },
  { off: 13860, w: 14, h: 63, advance: 17, bx: -1, by: -50 },
  { off: 13986, w: 32, h: 47, advance: 36, bx: 4, by: -47 },
  { off: 14174, w: 8, h: 47, advance: 17, bx: 4, by: -47 },
  { off: 14221, w: 49, h: 36, advance: 58, bx: 4, by: -36 },
  { off: 14473, w: 31, h: 36, advance: 39, bx: 4, by: -36 },
  { off: 14617, w: 33, h: 37, advance: 39, bx: 3, by: -36 },
  { off: 14802, w: 33, h: 49, advance: 40, bx: 4, by: -36 },
  { off: 15047, w: 33, h: 49, advance: 40, bx: 3, by: -36 },
  { off: 15292, w: 20, h: 36, advance: 25, bx: 4, by: -36 },
  { off: 15400, w: 30, h: 37, advance: 35, bx: 3, by: -36 },
  { off: 15548, w: 20, h: 44, advance: 23, bx: 1, by: -44 },
  { off: 15680, w: 31, h: 36, advance: 39, bx: 4, by: -36 },
  { off: 15824, w: 35, h: 36, advance: 38, bx: 1, by: -36 },
  { off: 16004, w: 50, h: 36, advance: 54, bx: 2, by: -36 },
  { off: 16256, w: 33, h: 36, advance: 36, bx: 2, by: -36 },
  { off: 16436, w: 35, h: 49, advance: 38, bx: 1, by: -36 },
  { off: 16681, w: 28, h: 36, advance: 36, bx: 4, by: -36 },
  { off: 16825, w: 22, h: 59, advance: 29, bx: 4, by: -50 },
  { off: 17002, w: 7, h: 78, advance: 23, bx: 8, by: -63 },
  { off: 17080, w: 22, h: 59, advance: 29, bx: 3, by: -50 },
  { off: 17257, w: 33, h: 14, advance: 43, bx: 5, by: -26 },
];

/* 17393 bytes of packed 64px glyph data. */
const VALUE_B64 =
  'f8B/wH/Af8B/wH/Af8B/wH/Af8B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gAAAAAAAAAAA' +
  'AAAAAD8Af4B/wP/A/8D/wH/Af4A/AP8H+P8H+H8H+H8H+H8H+H8H+H8H+H8H+H8H+H8H+H8H+H8D+H8D+H8D8H8D8H8D8H8D' +
  '8H8D8H8D8AAPwA/gAA/AD8AAD8APwAAfwA/AAB/AD8AAH4AfwAAfgB/AAB+AH4AAH4AfgAA/gB+AAD8AH4AP/////h/////+' +
  'H/////4f/////h/////+H/////wf/////AB+AH8AAH4AfgAAfgB+AAD+AH4AAP4AfgAA/AB+AAD8AP4AAPwA/gAA/AD8AAD8' +
  'APwAf/////B/////8H/////w//////D/////8P/////w//////AD+AH4AAPwA/gAA/AD+AAD8AP4AAPwA/AAB/AD8AAH8APw' +
  'AAfgA/AAB+AH8AAH4AfwAAfgB+AAB+AH4AAAAPAAAAAA8AAAAADwAAAAAPAAAAAA8AAAAADwAAAAAfAAAAAf/8AAAH//8AAB' +
  '///8AAP///4AB////wAP////gB////+AH/jx/8A/8PB/wD/g8D/gP8DwP+B/wPAf4H/A8B/gf8DwAAB/wPAAAH/A8AAAP+Dw' +
  'AAA/+PAAAD/+8AAAH//wAAAP//wAAAf//4AAA///8AAA///8AAA///4AAA///wAAAP//gAAA///AAADx/8AAAPB/4AAA8D/g' +
  'AADwH+AAAPAf8P8A8B/w/wDwH/D/gPAf8P+A8B/gf8DwP+B/4PB/4H/w8f/gP////8Af////gB////+AD////wAD///8AAH/' +
  '//gAAD//4AAAAPAAAAAA8AAAAADwAAAAAPAAAAAA8AAAAADwAAAH/gAAAfgAD/8AAAPwAB//gAAH4AA//8AAB+AAf//gAA/A' +
  'AH8H4AAfgAB+B+AAH4AA/gPwAD8AAPwD8AB+AAD8A/AA/gAA/APwAPwAAPwD8AH4AAD8A/AD+AAA/APwA/AAAH4H8AfgAAB+' +
  'B+APwAAAfw/gD8AAAD//wB+AAAA//8A/AAAAH/+APwAAAAf/AH4AAAAB+AD8AAAAAAAA/AAAAAAAAfgAAAAAAAPwAAAAAAAD' +
  '8AH8AAAAB+AH/wAAAA/AD/+AAAAPwB//wAAAH4A//+AAAD8Afw/gAAB/AH4H4AAAfgB+A/AAAPwAfgPwAAH8APwD8AAB+AD8' +
  'A/AAA/AA/APwAAfgAPwD8AAH4AD8A/AAD8AAfgPwAB+AAH4D8AAfgAB+B+AAPwAAfw/gAH4AAD//4AB+AAAf/8AA/AAAH/+A' +
  'AfgAAAf/AAAAAAAB/AAAH/gAAAB//gAAAf//AAAD//+AAAP//8AAB///4AAH/D/gAA/wD+AAD/AP8AAP4AfwAA/gB/AAD+AH' +
  '8AAP4A/wAA/wD+AAD/Af4AAH+D/AAAf4/8AAB/3/gAAD//8AAAH//gAAAf/8AAAA//gAAAD/4AAAAf/gAAAH//AAAA//+Afw' +
  'H//4B/A///wH8D/j/gfwf8H/B/B/gP+P8P+Af8/g/wB//+D/AD//4P8AH//A/wAP/8D/AAf/wP+AA/+A/4AD/wB/wAf/gH/4' +
  'P/+AP////8Af////4A/////wB///z/gD//8H/AB/+AP8//9/f39/f39/f39/f39/f39/fwD+Af4D/AP8A/wH+Af4D/AP8A/w' +
  'H+Af4B/gP+A/wD/AP8B/wH+Af4B/gH+A/4D/gP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/4D/gH+Af4B/gH/Af8A/wD/A' +
  'P+Af4B/gH/AP8A/wB/gH+Af8A/wD/AH+AP7+AP8A/wB/gH+AP8A/wD/gH+Af4B/wD/AP8A/4B/gH+Af4B/gH/AP8A/wD/AP8' +
  'A/4D/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4D/gP+A/wD/AP8A/wH/Af4B/gH+A/4D/AP8B/wH+A/4D/AP8B/gH+A/wD/AP4A' +
  'AD4AAAA+AAAAPgAAAD4AAAA+AAAwPgYAeD4eAH4+PwD/Pv8A////gH///gAf//gAB//gAAH/gAAD/8AAD//wAD///AD///8A' +
  '/77/gP4+fwB8Ph8AMD4OACA+AAAAPgAAAD4AAAA+AAAAPgAAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AA' +
  'AA/gAAAP4AAAD+AA/////v////7////+/////v////7////+/////gAP4AAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AA' +
  'AA/gAAAP4AAAD+AAAA/gAAAP4AAf4D/gP8A/wD/AP4A/gD+Af4B/AH8AfwB+AH4A/gD+APwA/AD8AH//+P//+P//+P//+P//' +
  '+P//+P//+D8Af4B/wP/A/8D/wH/Af4A/AAAA/AAB/AAB/AAD+AAD+AAD+AAH+AAH8AAH8AAH8AAP8AAP4AAP4AAP4AAfwAAf' +
  'wAAfwAAfwAA/gAA/gAA/gAB/gAB/AAB/AAB/AAD/AAD+AAD+AAD+AAH8AAH8AAH8AAH8AAP4AAP4AAP4AAP4AAfwAAfwAAfw' +
  'AA/wAA/gAA/gAA/gAB/gAB/AAB/AAB/AAD+AAD+AAD+AAD+AAH8AAH8AAH8AAP8AAP4AAAAP/wAAAD//wAAA///wAAH///gA' +
  'A////AAH///+AA//D/8AD/wD/wAf+AD/gB/wAP+AP+AAf8A/4AB/wD/AAD/gf8AAP+B/wAAf4H+AAB/gf4AAH+B/gAAf8P+A' +
  'AB/w/4AAH/D/gAAf8P+AAA/w/4AAD/D/gAAP8P+AAA/w/4AAD/D/gAAf8P+AAB/w/4AAH/B/gAAf8H+AAB/gf4AAH+B/wAAf' +
  '4H/AAD/gP8AAP+A/4AB/wD/gAH/AH/AA/4Af+AD/gA/8A/8AD/8P/wAH///+AAP///wAAf//+AAA///wAAA//8AAAA//AAAA' +
  'f+AA/+AB/+AD/+AP/+Af/+A//+D//+D/3+D/H+D+H+D8H+DwH+DgH+DAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AA' +
  'H+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAf/wA' +
  'Af//AAP//8AP///gH///8B////g/+D/8f+AP/H/AB/x/gAP+/4AB/v8AAf7/AAH+/wAB/gAAAf4AAAH+AAAB/gAAA/4AAAP8' +
  'AAAH/AAAD/gAAA/4AAAf8AAAP+AAAH/gAAD/wAAB/4AAA/8AAAf+AAAP/AAAH/gAAD/wAAB/4AAA/8AAAf+AAAP/AAAH/gAA' +
  'D/wAAB/4AAA/+AAAf////////////////////////////////////wAf/wAAAH//wAAB///wAAP///gAB////AAP///+AB/+' +
  'D/4AP/AD/wA/4AH/AD/AAP8AP8AA/4B/gAB/gAAAAH+AAAAAf4AAAAD/gAAAAP8AAAAB/wAAAAP+AAAAB/4AAAf//AAAD//w' +
  'AAAP/+AAAA//gAAAD//wAAAP//wAAA///gAAAA//AAAAAf+AAAAA/4AAAAB/wAAAAH/AAAAAP8AAAAA/wAAAAD/Af4AAP8D/' +
  'gAA/wH+AAH/Af8AAf8B/4AD/wD/wA/+AP/4P/wAf////AA////4AB////AAD///wAAD//+AAAD//AAAAAA/+AAAAH/4AAAAf' +
  '/gAAAD/+AAAAf/4AAAB//gAAAP/+AAAB//4AAAH//gAAA//+AAAD/f4AAAf5/gAAD/n+AAAP8f4AAB/h/gAAP+H+AAA/wf4A' +
  'AH+B/gAAf4H+AAD/Af4AAf8B/gAB/gH+AAP8Af4AB/wB/gAH+AH+AA/wAf4AH/AB/gAf4AH+AD/gAf4AP8AB/gB/gAH+AP//' +
  '///w//////j/////+P/////4//////j/////+P/////4AAAD/gAAAAP+AAAAA/4AAAAD/gAAAAP+AAAAA/4AAAAD/gAAAAP+' +
  'AAAAA/4AD////gAf///+AB////4AH////gAf///+AB////4AH////AAfwAAAAB/AAAAAH8AAAAAfwAAAAD/AAAAAP8AAAAA/' +
  'wAAAAD/AAAAAP8D4AAA/h/8AAD+f/8AAP7//4AA////4AH////gAf////AB/+B/+AH/gB/4AB4AD/wAAAAH/AAAAAP8AAAAA' +
  '/4AAAAD/gAAAAH+AAAAAf4AAAAB/gAAAAH+AAAAAf4D/AAD/gP+AAP8Af4AA/wB/wAH/AH/AA/4AP/AH/gA//B/8AB////wA' +
  'D///+AAH///wAAP//8AAAP//gAAAP/wAAAAH/wAAAD//4AAAf//wAAD///wAAf///gAD///+AAf///8AD/wD/4AP+AD/gB/w' +
  'AH/AH+AAf8A/4AA/wD/AAAAAP8AAAAB/gAAAAH+AAAAAf4B/AAB/g//gAH+P//AAfx///AD/P//+AP9///8A/////wD//AP/' +
  'gP/4Af+A//AA/8D/4AB/wP/AAD/A/8AAP8D/wAA/4H+AAB/gf4AAH+B/gAAf4H+AAD/gf8AAP8A/wAA/wD/gAH/AP+AAf8Af' +
  '8AD/gB/4A/+AD/8P/wAH///+AAP///wAAf//+AAA///wAAA//+AAAA//AAD////+/////v////7////+/////v////7////+' +
  'AAAD/gAAA/4AAAf8AAAH/AAAD/gAAA/4AAAf8AAAH/AAAD/gAAA/4AAAf8AAAH/AAAD/gAAA/4AAAf8AAAH/AAAD/gAAA/4A' +
  'AAf8AAAH/AAAD/gAAA/4AAAf8AAAH/AAAD/gAAA/4AAAf8AAAH/AAAD/gAAA/4AAAf8AAAH/AAAD/gAAA/4AAAf8AAAH/AAA' +
  'D/gAAA/4AAAP8AAAH/AAAAAf/wAAAH//wAAB///wAAP///gAB////AAP///+AB/+D/8AH/gD/wA/8AH/AD/gAP+AP8AAf4A/' +
  'wAB/gD/AAH+AP8AAf4A/wAB/gB/gAP8AH+AA/wAf8AH+AA/8B/4AB////AAD///4AAD//+AAAH//gAAB///wAAf///wAD///' +
  '/gAf/Af/AD/wAf+AP+AA/4B/wAB/wH+AAH/Af4AAP8D/gAA/4P+AAD/g/4AAP+D/gAA/4P+AAD/gf8AAf8B/4AD/wH/wAf+A' +
  'P/4P/4Af////AA////4AB////AAD///4AAD//+AAAD//AAAAH/4AAAD//4AAAf//4AAD///wAA////gAD////AAf/h/+AD/4' +
  'A/4AP+AB/wB/wAD/AH/AAP+Af4AAf4B/gAB/wP8AAD/A/wAAP8D/AAA/wP8AAD/A/4AAf8D/gAB/4H+AAH/gf8AA/+B/4AH/' +
  '4D/wA//gP/wP/+Af///f4A///5/gD///H+AD//4/wAH//D/AAH/wP8AAD4A/wAAAAD/AAAAAP8AAAAB/gH+AAH+Af4AA/4B/' +
  'wAD/AH/AAf8AP+AD/gA/8Af+AB/8H/wAD///+AAP///wAAf//+AAAf//wAAA//+AAAA//AAAPwB/gH/A/8D/wP/Af8B/gD8A' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwB/gH/A/8D/wP/Af8B/gD8AD8Af4D/gP/A/8D/wP+Af4A/AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gP+A/wD/AP8A/gD+AP4B/gH8AfwB/AH4AfgD+AP4A/AD8APwAAAAAAgAA' +
  'AA4AAAA+AAAA/gAAB/4AAB/+AAB//gAB//4AB//8AB//8AB//4AD//4AD//4AD//wAD//wAA//wAAP/gAAD/wAAA/+AAAP/8' +
  'AAD//wAAP//AAA//+AAD//4AAP//gAAf/+AAB//8AAH//gAAf/4AAB/+AAAH/gAAAf4AAAA+AAAADgAAAAJ////8/////v//' +
  '//7////+/////v////7////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB////8/////v////7////+/////v//' +
  '//7////+gAAAAOAAAAD4AAAA/gAAAP/AAAD/8AAA//wAAP//AAB//8AAH//wAAP//gAA//+AAD//4AAH//gAAf/+AAB//gAA' +
  'D/4AAAf+AAAP/gAAP/4AAf/+AAf/+AAf/+AA//+AA//+AA//+AB//8AA//8AAP/8AAD/8AAA/8AAAP8AAAD4AAAA4AAAAIAA' +
  'AAAA//AAA//+AA///wAf//+AP///wH///+B/8P/g/8A/8P+AH/D/AA/w/wAP+P8AD/j+AA/4AAAP+AAAD/AAAB/wAAAf8AAA' +
  'P/AAAH/gAAH/wAAD/4AAB/8AAA/+AAAf+AAAP/AAAD/gAAA/wAAAf4AAAH+AAAB/gAAAf4AAAH+AAAB/AAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAA/AAAAf4AAAP/AAAD/wAAA/8AAAP/AAAD/wAAAf4AAAD8AAAAAAP/wAAAAAAAf//8AAAAAAP///8AAAAAD' +
  '////8AAAAAf////8AAAAH/////8AAAA//////4AAAH/+AAf/wAAA//AAAP/gAAH/wAAAP/AAA/8AAAAf+AAH/gAAAAf4AAf8' +
  'AAAAA/wAD/gAAAAB/AAP8AA8AAH+AB/gA/+PwP4AH8AH/+/AfwA/wB///8B/AD+AP///wH+AP4A////AP4B/gH///8A/gH8A' +
  '/8D/wD+AfwD/AD/AH4B/AP4AH8AfwH8B/AAfwB/A/wH8AA/AH8D+AfgAD8AfwP4B+AAPwB/A/gH4AA/AH8D+AfgAD8AfwP4B' +
  '+AAPwB/A/gH4AA/AH4D+AfgAD8AfgP4B+AAPwB+A/wH8AA/AP4B/AfwAH8A/gH8B/gAfwD+AfwD+AD/gPwB/AP+A/+B/AH+A' +
  'f///8P4AP4B//////gA/gD//9//8AD/AH//z//wAP8AP/+H/+AAf4Af/gP/gAB/wAP4AP4AAD/AAAAAAAAAP+AAAAAAAAAf+' +
  'AAAAAAAAA/8AAAAAAAAB/8AAAAAAAAH/8AAAYAAAAP/+AAPgAAAAP/////AAAAAf////8AAAAA/////wAAAAA/////gAAAAA' +
  '////8AAAAAAf//+AAAAAAAD/8AAAAAAA/+AAAAAB/+AAAAAB/+AAAAAB//AAAAAD//AAAAAD//AAAAAD//gAAAAH//gAAAAH' +
  '+/gAAAAH8/wAAAAP8/wAAAAP8/wAAAAf8f4AAAAf4f4AAAAf4f8AAAA/4f8AAAA/wP8AAAA/wP+AAAB/wP+AAAB/wH+AAAB/' +
  'gH/AAAD/gH/AAAD/gD/AAAD/AD/gAAH/AD/gAAH/AB/gAAH+AB/wAAP+AB/wAAP////wAAP////4AAf////4AAf////8AAf/' +
  '///8AA/////8AA/////+AA/wAAP+AB/wAAP+AB/wAAH/AD/gAAH/AD/gAAH/AD/gAAD/gH/AAAD/gH/AAAD/gH/AAAB/wP+A' +
  'AAB/wP+AAAB/wP+AAAA/4P///gAA////wAD////wAP////gA/////AD////+AP////4A/wAH/wD/AAP/AP8AAf8A/wAA/wD/' +
  'AAD/gP8AAP8A/wAA/wD/AAD/AP8AAP8A/wAB/wD/AAP+AP8AD/wA////+AD////wAP///4AA////wAD////4AP////wA////' +
  '/gD/AAf/AP8AAf+A/wAA/4D/AAB/wP8AAH/A/wAAP8D/AAA/wP8AAD/A/wAAP8D/AAA/wP8AAH/A/wAAf8D/AAD/wP8AA/+A' +
  '/////4D/////AP////4A/////AD////4AP///+AA////AAAAAf/wAAAAD//+AAAAP///gAAAf///wAAA////4AAB////8AAD' +
  '////+AAH/////AAP/4Af/gAP/gAH/gAf+AAD/wAf8AAB/wA/8AAB/wA/4AAA/4B/wAAA/4B/wAAAf4B/wAAAAAB/gAAAAAB/' +
  'gAAAAAD/gAAAAAD/gAAAAAD/gAAAAAD/gAAAAAD/gAAAAAD/gAAAAAD/gAAAAAD/gAAAAAD/gAAAAAB/gAAAAAB/gAAAAAB/' +
  'wAAAAAB/wAAAf4B/wAAA/4A/4AAA/4A/8AAB/wAf8AAB/wAf+AAD/wAP/gAH/gAP/4Af/AAH/////AAD////+AAB////8AAA' +
  '////4AAAf///wAAAP///gAAAD//+AAAAAf/wAAD///gAAP///4AA////4AD////4AP////wA/////gD/////AP8AD/+A/wAB' +
  '/8D/AAD/wP8AAD/g/wAAP/D/AAAf8P8AAA/w/wAAD/j/AAAH+P8AAAf4/wAAB/j/AAAH/P8AAAP8/wAAA/z/AAAD/P8AAAP8' +
  '/wAAA/z/AAAD/P8AAAP8/wAAA/z/AAAH/P8AAAf8/wAAB/j/AAAH+P8AAAf4/wAAD/j/AAAP8P8AAB/w/wAAP/D/AAB/4P8A' +
  'AP/A/wAB/8D/AA//gP////8A/////gD////8AP////gA////4AD///+AAP//+AAA/////P////z////8/////P////z////8' +
  '/////P8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD////w////8P////D////w' +
  '////8P////D////w/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP////z////8' +
  '/////P////z////8/////P////z////8/////P////z////8/////P////z////4/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA' +
  '/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD////g////4P///+D////g////4P///+D////g/wAAAP8AAAD/AAAA' +
  '/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAB//AAAAAP' +
  '//4AAAA///+AAAB////AAAD////gAAH////wAAP////4AAf////8AA//gB/+AA/+AAf+AB/4AAP/AB/wAAH/AD/wAAH/gD/g' +
  'AAD/gH/AAAD/gH/AAAAAAH/AAAAAAH+AAAAAAH+AAAAAAP+AAAAAAP+AAAAAAP+AAAAAAP+AAf//wP+AAf//wP+AAf//wP+A' +
  'Af//wP+AAf//wP+AAf//wH+AAf//gH+AAAB/gH/AAAB/gH/AAAB/gH/AAAB/gD/gAAD/gD/wAAD/gB/wAAH/AB/4AAP/AA/+' +
  'AAf+AA//gB/+AAf////8AAP////4AAH////4AAD////wAAB////AAAA///+AAAAP//4AAAAB//gAAP8AAAP8/wAAA/z/AAAD' +
  '/P8AAAP8/wAAA/z/AAAD/P8AAAP8/wAAA/z/AAAD/P8AAAP8/wAAA/z/AAAD/P8AAAP8/wAAA/z/AAAD/P8AAAP8/wAAA/z/' +
  'AAAD/P8AAAP8//////z//////P/////8//////z//////P/////8//////z/AAAD/P8AAAP8/wAAA/z/AAAD/P8AAAP8/wAA' +
  'A/z/AAAD/P8AAAP8/wAAA/z/AAAD/P8AAAP8/wAAA/z/AAAD/P8AAAP8/wAAA/z/AAAD/P8AAAP8/wAAA/z/AAAD/P8AAAP8' +
  '/wAAA/z//////////////////////////////////////////////////////////////wAAA/wAAAP8AAAD/AAAA/wAAAP8' +
  'AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8' +
  'AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/z/gAP8/4AD/P+AA/z/gAP8f4AD/H+AA/x/wAf8f8AH/D/gD/g/+D/4' +
  'H///8B///+AP///gB///gAH//wAAf/wA/wAAH/z/AAA/+P8AAH/w/wAAf+D/AAD/wP8AAf+A/wAD/wD/AAf/AP8AD/4A/wAf' +
  '/AD/AB/4AP8AP/AA/wB/4AD/AP/AAP8B/4AA/wP/gAD/A/8AAP8H/gAA/w/8AAD/H/gAAP8/8AAA/z/4AAD/f/gAAP///AAA' +
  '///+AAD///8AAP/9/wAA//n/gAD/8P/AAP/gf8AA/8B/4AD/gD/wAP+AH/AA/wAf+AD/AA/8AP8AB/wA/wAH/gD/AAP/AP8A' +
  'Af8A/wAB/4D/AAD/wP8AAH/g/wAAf+D/AAA/8P8AAB/4/wAAH/j/AAAP/P8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/' +
  'AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/' +
  'AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD////w////+P////j/' +
  '///4////+P////j////4//AAAAf/gP/4AAAP/4D/+AAAD/+A//wAAB//gP/8AAAf/4D//AAAH/+A//4AAD//gP/+AAA//4D/' +
  '/gAAP/+A//8AAH//gP//AAB//4D/fwAAf3+A/3+AAP9/gP9/gAD/f4D/f8AA/n+A/z/AAf5/gP8/wAH+f4D/P+AD/n+A/x/g' +
  'A/x/gP8f4AP8f4D/H/AH/H+A/w/wB/h/gP8P8Af4f4D/D/gP+H+A/wf4D/B/gP8H+A/wf4D/B/wf8H+A/wP8H+B/gP8D/B/g' +
  'f4D/A/4fwH+A/wH+P8B/gP8B/j/Af4D/AP4/gH+A/wD/P4B/gP8A/3+Af4D/AH9/AH+A/wB/fwB/gP8Af/8Af4D/AD/+AH+A' +
  '/wA//gB/gP8AH/wAf4D/AB/8AH+A/wAf/AB/gP8AD/gAf4D/AA/4AH+A/wAP+AB/gP8AB/AAf4D/gAAD/v/AAAP+/+AAA/7/' +
  '4AAD/v/wAAP+//gAA/7/+AAD/v/8AAP+//wAA/7//gAD/v//AAP+//8AA/7/f4AD/v9/gAP+/z/AA/7/P+AD/v8f4AP+/x/w' +
  'A/7/D/gD/v8P+AP+/wf8A/7/B/wD/v8D/gP+/wH/A/7/Af8D/v8A/4P+/wB/w/7/AH/D/v8AP+H+/wA/4f7/AB/x/v8AD/H+' +
  '/wAP+f7/AAf5/v8AA/3+/wAD/f7/AAH//v8AAf/+/wAA//7/AAB//v8AAH/+/wAAP/7/AAAf/v8AAB/+/wAAD/7/AAAP/v8A' +
  'AAf+AAH/8AAAAA///gAAAD///4AAAH///8AAAP///+AAAf////AAA/////gAB/////wAD/+AH/4AD/4AB/8AH/gAA/8AH/AA' +
  'Af+AP/AAAP+AP+AAAP+Af8AAAH/Af8AAAH/Af8AAAD/Af4AAAD/Af4AAAD/g/4AAAD/g/4AAAD/g/4AAAD/g/4AAAD/g/4AA' +
  'AB/g/4AAAD/g/4AAAD/g/4AAAD/g/4AAAD/gf4AAAD/gf4AAAD/Af8AAAD/Af8AAAH/Af8AAAH/AP+AAAP+AP/AAAP+AH/AA' +
  'Af+AH/gAA/8AD/4AB/8AD/+AH/4AB/////wAA/////gAAf////gAAP///+AAAH///8AAAD///4AAAA///gAAAAH/8AAA///8' +
  'AAD///+AAP///+AA////8AD////4AP////wA/////gD/AA//AP8AA/8A/wAB/4D/AAD/gP8AAP+A/wAAf4D/AAB/gP8AAH+A' +
  '/wAAf4D/AAB/gP8AAH+A/wAA/4D/AAD/gP8AAP+A/wAB/wD/AAP/AP8AD/4A/////gD////8AP////gA////8AD////AAP//' +
  '/wAA///wAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAA' +
  'AP8AAAAA/wAAAAD/AAAAAAAB//AAAAAP//4AAAA///+AAAB////AAAD////gAAH////4AAP////4AAf////8AA//gB/+AA/+' +
  'AAf/AB/4AAP/AB/wAAH/gD/wAAD/gD/gAAD/gH/AAAB/wH/AAAB/wH/AAAA/wH+AAAA/wH+AAAA/4P+AAAA/4P+AAAA/4P+A' +
  'AAA/4P+AAAA/4P+AAAAf4P+AAAAf4P+AAAA/4P+AAAA/4P+AAAA/4H+AAAA/4H+AAAA/wH/AAAA/wH/AH+B/wH/AD/B/wD/g' +
  'B/D/gD/wA/j/gB/wA/3/AB/4Af//AA/+AP/+AA//gH/+AAf////8AAP////4AAH////wAAD////wAAB////wAAA////4AAAP' +
  '///8AAAB//P+AAAAAAH+AAAAAAD/AAAAAAB/gAAAAAA/gP///AAA////gAD////gAP////gA/////AD////8AP////4A/wAH' +
  '/wD/AAP/AP8AAf+A/wAA/4D/AAD/gP8AAH+A/wAAf4D/AAB/gP8AAH+A/wAAf4D/AAB/gP8AAP+A/wAA/4D/AAH/gP8AA/8A' +
  '/wAP/wD////+AP////wA/////AD////wAP///+AA////gAD////AAP8Af8AA/wA/4AD/AD/gAP8AH/AA/wAf8AD/AA/4AP8A' +
  'D/wA/wAH/AD/AAf+AP8AA/4A/wAD/wD/AAH/AP8AAf+A/wAA/4D/AAB/wP8AAH/A/wAAP+AAD/+AAAB///AAAf//+AAD///+' +
  'AAf///8AD////wAf/gf/gB/4AP/AP+AAf8A/4AA/4D/AAD/gf8AAH+B/wAAf4H/AAAAAf8AAAAB/4AAAAD/wAAAAP/gAAAA/' +
  '/wAAAB//4AAAH//+AAAP///AAAf///AAAf///AAAf//+AAAf//8AAAP//4AAAD//wAAAB//gAAAA/+AAAAB/4AAAAD/gAAAA' +
  'H/AAAAAf8P8AAB/w/4AAH/D/gAAf4H+AAD/gf8AAP+B/4AD/4D/4Af/AP////4Af////gA////8AB////AAB///4AAB//+AA' +
  'AAf+AAD/////+P/////4//////j/////+P/////4//////j/////8AAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD' +
  '/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wA' +
  'AAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAA' +
  'A/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAA/wAAB/j/AAAH+P8AAAf4/wAAB/j/AAAH+P8AAAf4/wAAB/j/AAAH+P8AAAf4/wAA' +
  'B/j/AAAH+P8AAAf4/wAAB/j/AAAH+P8AAAf4/wAAB/j/AAAH+P8AAAf4/wAAB/j/AAAH+P8AAAf4/wAAB/j/AAAH+P8AAAf4' +
  '/wAAB/j/AAAH+P8AAAf4/wAAB/j/AAAH+P8AAAf4/wAAB/j/AAAH+P8AAAf4/4AAD/j/gAAP+P/AAB/4f+AAP/B/8AB/8D/8' +
  'Af/wP////+Af////wA////+AB////4AD///+AAH///wAAH//8AAAD//AAP+AAAA/4P+AAAB/4P/AAAB/wH/AAAB/wH/AAAD/' +
  'gD/gAAD/gD/gAAD/gD/gAAH/AB/wAAH/AB/wAAH/AB/wAAP+AA/4AAP+AA/4AAP+AA/4AAf8AAf8AAf8AAf8AAf8AAf8AAf4' +
  'AAP+AA/4AAP+AA/4AAP+AA/wAAH/AB/wAAH/AB/wAAD/AB/gAAD/gD/gAAD/gD/gAAB/gD/AAAB/wH/AAAB/wH+AAAA/wH+A' +
  'AAA/wP+AAAA/4P8AAAAf4P8AAAAf4P8AAAAf8f4AAAAP8f4AAAAP8f4AAAAP8/wAAAAH+/wAAAAH+/wAAAAD//gAAAAD//gA' +
  'AAAD//gAAAAB//AAAAAB//AAAAAB//AAAAAA/+AAAAAA/+AAAP+AAD/gAAf8/4AAP+AAD/j/gAA/8AAP+P+AAH/wAA/4f8AA' +
  'f/AAD/h/wAB/8AAf8H/AAH/4AB/wP8AA//gAH/A/4AD/+AAf4D/gAP/4AD/gP+AA//wAP+Af4AH//AA/4B/wAf38AD/AH/AB' +
  '/fwAf8Af8AH9/gB/wA/wA/z+AH/AD/gD/P4Af4AP+AP4/gB/gAf4A/j/AP+AB/gH+P8A/wAH+Af4fwD/AAf8B/B/AP8AA/wH' +
  '8H+B/wAD/A/wf4H+AAP8D/A/gf4AA/4P4D+B/gAB/g/gP8P+AAH+H+A/w/wAAf4f4B/D/AAB/x/AH8P8AAD/H8Af4/wAAP8f' +
  'wB/n+AAA/z/AD+f4AAB/P4AP5/gAAH8/gA/n8AAAf7+AB+fwAAB/vwAH//AAAD//AAf/8AAAP/8AB//gAAA//wAD/+AAAD/+' +
  'AAP/4AAAH/4AA//gAAAf/gAD/8AAAB/+AAH/wAAAH/wAAf/AAAAP/AAB/8AAAA/8AAH/gAB/4AAB/4A/8AAB/wAf8AAD/wAf' +
  '+AAH/gAP/AAH/AAH/AAP/AAH/gAf+AAD/wAf8AAB/wA/8AAB/4B/4AAA/4B/wAAAf8D/wAAAf+D/gAAAP+H/AAAAH/H+AAAA' +
  'H/P+AAAAD/v8AAAAB//4AAAAB//4AAAAA//wAAAAAf/gAAAAAf/gAAAAAP/AAAAAAP/AAAAAAf/gAAAAAf/wAAAAA//wAAAA' +
  'B//4AAAAB//8AAAAD//8AAAAH/P+AAAAH/P/AAAAP+H/AAAAf8D/gAAA/8D/wAAA/4B/4AAB/wA/4AAD/wA/8AAD/gAf+AAH' +
  '/AAP+AAP/AAP/AAP+AAH/gAf8AAD/gA/8AAD/wB/4AAB/4B/wAAA/4D/wAAA/8D/wAAA/8D/wAAA/4B/4AAB/4A/4AAD/wA/' +
  '8AAD/gAf8AAH/gAf+AAH/AAP+AAP/AAH/AAP+AAH/gAf+AAD/gAf8AAD/wA/4AAB/wA/4AAA/4B/wAAA/4D/wAAAf8D/gAAA' +
  'f8H/AAAAP+H/AAAAH+P+AAAAH/P+AAAAD/P8AAAAD//4AAAAB//4AAAAA//wAAAAA//wAAAAAf/gAAAAAf/gAAAAAP/AAAAA' +
  'AP+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAA' +
  'AH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAAAAH+AAAD/////wP/////A/////8D/////wP/////A/////8D/' +
  '////gAAAAP8AAAAB/wAAAAP+AAAAB/wAAAAH/AAAAA/4AAAAH/AAAAA/8AAAAD/gAAAAf8AAAAD/wAAAAP+AAAAB/wAAAAP/' +
  'AAAAA/4AAAAH/AAAAA/4AAAAD/gAAAAf8AAAAD/gAAAAP+AAAAB/wAAAAP+AAAAA/4AAAAH/AAAAA/4AAAAD/gAAAAf8AAAA' +
  'D/gAAAAP8AAAAB/wAAAAP+AAAAB/wAAAAH/////A/////8D/////wP/////A/////8D/////wP/////A//z//P/8//z//P/8' +
  '//z/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A' +
  '/wD/AP8A/wD/AP8A/wD/AP8A/wD//P/8//z//P/8//z//H4AAP4AAH8AAH8AAH8AAH+AAD+AAD+AAD+AAD/AAB/AAB/AAB/A' +
  'AA/gAA/gAA/gAA/gAAfwAAfwAAfwAAfwAAP4AAP4AAP4AAP8AAH8AAH8AAH8AAH+AAD+AAD+AAD+AAB/AAB/AAB/AAB/AAA/' +
  'gAA/gAA/gAA/wAAfwAAfwAAfwAAf4AAP4AAP4AAP4AAH8AAH8AAH8AAH8AAD+AAD+AAD+AAD/AAB/AAB/P/+//7//v/+//7/' +
  '/n/+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B' +
  '/gH+Af4B/gH+Af4B/gH+Af4B/gH+f/7//v/+//7//v/+//4AfwAAAP8AAAD/gAAB/4AAAf/AAAP/wAAD/+AAA/fgAAfn8AAH' +
  '4/AAD+P4AA/B+AAfwfwAH4D8AD+A/gA/AP4AfwB+AH8AfwD+AD8A/gA/gPwAH4D////8/////P////z////8/////P////z/' +
  '///8/wB/AH+AP4AfwB/AD+AH4AfwA/AAD/gAAH//AAH//8AH///gD///8B////gf///4P/AP/D/gB/w/wAP8A4AD/AAAA/wA' +
  'AAP8AAAD/AAAB/wAA//8AH///AP///wP///8H////D//g/x/8AP8f8AD/H+AA/x/AAP8/wAD/P8AB/z/gAf8f4AP/H/gP/x/' +
  '///8P//9/D//+fwf//n8D//x/AP/wfwA/wAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA' +
  '/wAAAAD/AAAAAP8B/AAA/wf/gAD/D//gAP8f//AA/z//+AD/f//8AP////wA//gP/gD/8Af+AP/gA/8A/8AB/wD/wAD/AP+A' +
  'AP+A/4AA/4D/gAD/gP8AAH+A/wAAf4D/AAB/gP8AAH+A/wAAf4D/AAB/gP+AAH+A/4AA/4D/gAD/gP+AAP8A/8AB/wD/wAH/' +
  'AP/gA/8A//AH/gD//B/+AP////wA/3//+AD/P//wAP8f/+AA/w//wAD/A/8AAAAP+AAAf/8AAf//gAP//+AH///wD///+B//' +
  '//wf+A/8P/AH/j/gA/5/wAH+f4AB/n+AAOD/gAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/gAAA/4AAAH+A' +
  'AOB/gAD+f8AB/j/gA/4/8Af+H/gP/B////wP///4B///8AP//+AB///AAH//AAAP+AAAAAB/gAAAAH+AAAAAf4AAAAB/gAAA' +
  'AH+AAAAAf4AAAAB/gAAAAH+AAAAAf4AAAAB/gAAAAH+AAD/Af4AA//B/gAP/+H+AB//8f4AP//5/gB///3+AH////4A/+A//' +
  'gD/gB/+Af+AD/4B/wAH/gH+AAf+A/4AA/4D/gAD/gP8AAP+A/wAAf4D/AAB/gP8AAH+A/wAAf4D/AAB/gP8AAH+A/wAA/4D/' +
  'gAD/gP+AAP+A/4AA/4B/wAH/gH/AAf+Af+AD/4A/8Af/gD/8H/+AH////4AP//5/gAf//n+AA//8f4AB//h/gAB/4H+AAA/w' +
  'AAB//gAB//+AA///wAf//+AP///wH///+B/4D/w/4Af8P8AD/n+AAf5/gAH+fwAA//8AAP//AAD/////////////////////' +
  '/////////////wAAAP8AAAD/AAAA/wAAAH+AAAB/gADgf8AB/j/gA/4f+Af+H////A////wH///4A///8AH//8AAf/8AAA/4' +
  'AAAB8AAf/gA//gB//gD//AH//AH//AP/AAP+AAP8AAP8AAP8AAP8AAP8AP///P///P///P///P///P///P//+AP8AAP8AAP8' +
  'AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8' +
  'AAP8AAP8AAAfwH+AAP/wf4AD//h/gAf//H+AD//+f4Af//9/gB////+AP/gP/4A/8Af/gH/gA/+Af8AB/4B/gAH/gP+AAP+A' +
  '/4AA/4D/AAD/gP8AAH+A/wAAf4D/AAB/gP8AAH+A/wAAf4D/AAB/gP8AAP+A/4AA/4D/gAD/gP+AAP+Af8AB/4B/wAP/gH/g' +
  'B/+AP/gP/4A/////gB///3+AD//+f4AH//x/gAP/+H+AAP/wf4AAP8B/gAAAAH+AAAAA/4AAAAD/AAMAAP8AP8AB/wB/4Af+' +
  'AD////4AH////AAP///4AAf///AAA///4AAA//+AAAAf+AAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA' +
  '/wAAAP8AAAD/AfwA/wf/gP8f/8D/P//w/z//8P9///j////8//Af/P/gB/z/wAf8/4AD/v+AA/7/gAH+/4AB/v8AAf7/AAH+' +
  '/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+' +
  '/wAB/v8AAf4+AH8A/4D/gP+A/4D/gH8APgAAAAAAAAAAAAAA/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A' +
  '/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8AAeAD+Af8B/wH/Af8B/wD+AHgAAAAAAAAAAAAAAf4B/gH+Af4' +
  'B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4B/gH+Af4' +
  'B/gP+P/4//D/8P/g/8D/APwA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAf+/wAP/P8A' +
  'H/j/AB/w/wA/4P8Af8D/AP/A/wH/gP8D/wD/A/4A/wf8AP8P+AD/H/AA/z/wAP//4AD//8AA///AAP//4AD///AA///wAP//' +
  '+AD/7/wA/8f8AP+H/gD/A/8A/wH/gP8B/4D/AP/A/wB/4P8AP+D/AD/w/wAf+P8AD/j/AA/8/wAH/v8AA///////////////' +
  '//////////////////////////////////////////////////8B+AAfwAD/B/4A//AA/x//Af/4AP8//4P//AD/P//H//4A' +
  '/3//z///AP///+///wD/8D//A/+A/8Af/gD/gP/AD/wA/4D/gA/4AH+A/4AH+AB/gP+AB/gAf4D/AAf4AH+A/wAH+AB/gP8A' +
  'B/gAf4D/AAf4AH+A/wAH+AB/gP8AB/gAf4D/AAf4AH+A/wAH+AB/gP8AB/gAf4D/AAf4AH+A/wAH+AB/gP8AB/gAf4D/AAf4' +
  'AH+A/wAH+AB/gP8AB/gAf4D/AAf4AH+A/wAH+AB/gP8AB/gAf4D/AAf4AH+A/wAH+AB/gP8AB/gAf4D/AAf4AH+A/wAH+AB/' +
  'gP8B/AD/B/+A/w//wP8f//D/P//w/3//+P9///j/8B/8/+AH/P/AB/z/gAP+/4AD/v+AAf7/gAH+/wAB/v8AAf7/AAH+/wAB' +
  '/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB' +
  '/gAP+AAAAH//AAAB///AAAP//+AAB///8AAP///4AB////wAH/gP/AA/8Af+AD/gA/4Af8AB/wB/gAD/AH+AAP8A/4AA/4D/' +
  'gAD/gP8AAH+A/wAAf4D/AAB/gP8AAH+A/wAAf4D/AAB/gP8AAH+A/4AA/4D/gAD/gH+AAP8Af4AA/wB/wAH/AD/gA/4AP/AH' +
  '/gAf+A/8AB////wAD///+AAH///wAAP//+AAAf//wAAAf/8AAAAP+AAA/wH8AAD/B/+AAP8P/+AA/x//8AD/P//4AP9///wA' +
  '/////AD/+A/+AP/wB/4A/+AD/wD/wAH/AP/AAP8A/4AA/4D/gAD/gP+AAP+A/wAAf4D/AAB/gP8AAH+A/wAAf4D/AAB/gP8A' +
  'AH+A/4AAf4D/gAD/gP+AAP+A/4AA/wD/wAH/AP/AAf8A/+AD/wD/8Af+AP/8H/4A/////AD/f//4AP8///AA/x//4AD/D//A' +
  'AP8D/wAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAD/AAAAAP8AAAAA/wAAAAAA' +
  'P8B/gAD/8H+AA//4f4AH//x/gA///n+AH///f4Af////gD/4D/+AP+AH/4B/4AP/gH/AAf+Af4AB/4D/gAD/gP+AAP+A/wAA' +
  '/4D/AAB/gP8AAH+A/wAAf4D/AAB/gP8AAH+A/wAAf4D/AAD/gP+AAP+A/4AA/4D/gAD/gH/AAf+Af8AB/4B/4AP/gD/wB/+A' +
  'P/wf/4Af////gA///n+AB//+f4AD//x/gAH/+H+AAH/gf4AAAAB/gAAAAH+AAAAAf4AAAAB/gAAAAH+AAAAAf4AAAAB/gAAA' +
  'AH+AAAAAf4AAAAB/gAAAAH+AAAAAf4AAAAB/gP8D8P8P8P8f8P8/8P9/8P9/8P//8P/4EP/wAP/AAP/AAP+AAP+AAP+AAP8A' +
  'AP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAAA/4AAB//wA' +
  'B///AA///4Af///AP///4D///+B/4D/wf8AP8H+AB/B/gAeAf4AAAH+AAAB/wAAAf/AAAD//AAAf//gAD///AAf//8AB///g' +
  'AD//8AAD//AAAD/4AAAP+AAAB/gCAAf8fwAH+P8AB/j/gA/4f+Af+H////A////wH///4A///8AH//8AAf/8AAA/4AAH+AAH' +
  '+AAH+AAH+AAH+AAH+AAH+AAH+AD//+D//+D//+D//+D//+D//+D//+AH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH' +
  '+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH/AAH/+AD//AD//AB//AA//AAP/D/AAH+/wAB/v8AAf7/AAH+' +
  '/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+/wAB/v8AAf7/AAH+' +
  '/wAB/v+AAf7/gAP+/4AD/n+AB/5/wAf+f+AP/n/4f/4///3+H//9/h//+f4P//H+B//h/gH/gf7/gAAf4H+AAD/gf8AAP8B/' +
  'wAA/wD/AAH/AP+AAf4Af4AB/gB/gAP+AH/AA/wAP8AD/AA/wAf8AD/gB/gAH+AH+AAf4A/wAB/wD/AAD/AP8AAP8B/gAAf4H' +
  '+AAB/gf4AAH+D/AAAP8P8AAA/w/wAAD/D+AAAH8f4AAAf5/AAAB/n8AAAD+fwAAAP7+AAAAf/4AAAB//gAAAH/8AAAAP/wAA' +
  'AA//AAAAD/4AAAAH/gAAAAf8AAD/AAf4AD/A/wAH+AB/wP+AD/gAf8D/gA/8AH+Af4AP/AB/gH+AD/wA/4B/wB/8AP8AP8Af' +
  '/gD/AD/AH/4A/wA/wB/+Af8AP8A//gH+AB/gP38B/gAf4D9/Af4AH+A/PwP8AA/gfz8D/AAP8H8/g/wAD/B+P4P8AA/wfh+D' +
  '+AAH8P4fh/gAB/j+H4f4AAf4/B/H8AAD+PwPx/AAA/j8D8/wAAP5/A/P8AAD/fgP7+AAAf34B+/gAAH9+Afv4AAB//AH/8AA' +
  'AP/wA//AAAD/8AP/wAAA//AD/8AAAP/gA/+AAAB/4AH/gAAAf+AB/4AAAH/AAf8AAAA/wAD/AAB/gAH/AH/AAf4AP+AD/gA/' +
  '4Af8AB/wB/wAD/AP+AAP+A/wAAf4H/AAB/wf4AAD/D/AAAH+P8AAAf5/gAAA/3+AAAB//wAAAH/+AAAAP/4AAAA//AAAAB/8' +
  'AAAAH/wAAAA//AAAAH/+AAAAf/8AAAD//wAAAf5/gAAB/n+AAAP8P8AAA/w/4AAH+B/gAA/4H/AAD/AP+AAf8Af4AD/gB/wA' +
  'P8AD/gB/wAP+AH+AAf8A/4AA/4D/gAAf4H+AAD/gf8AAP+A/wAA/wD/AAH/AP+AAf4Af4AB/gB/gAP+AH/AA/wAP8AD/AA/w' +
  'Af8AD/gB/gAH+AH+AAf4A/wAA/wD/AAD/AP8AAP8B/gAAf4H+AAB/gf4AAH+D/AAAP8P8AAA/w/gAAB/H+AAAH8f4AAAf5/A' +
  'AAA/n8AAAD+/wAAAP7+AAAAf/4AAAB//AAAAH/8AAAAP/wAAAA/+AAAAB/4AAAAH/gAAAAf8AAAAB/wAAAAH+AAAAAf4AAAA' +
  'D/gAAAAP8AAAAB/wAAAH/+AAAA//4AAAD//AAAAP/4AAAB//AAAAH/4AAAAP8AAAAP////D////w////8P////D////w////' +
  '8H///+AAAH/AAAB/wAAA/4AAAf8AAAP+AAAD/gAAB/wAAA/4AAAf+AAAH/AAAD/gAAB/wAAA/8AAAP+AAAH/AAAD/wAAB/4A' +
  'AAf8AAAP+AAAH/gAAD/wAAA/4AAAf///8P////D////w////8P////D////w////8AAA/AAH/AAf/AA//AB//AB//AD/+AD/' +
  'gAD/AAD/AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAP8AA/8AP/4AP/4AP/gAP8AAP8AAP/gAP/w' +
  'AP/4AA/8AAP8AAP+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAD/AAD/AAD/wAD/+AB//AB//AA/' +
  '/AAf/AAH/AAA/P7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+' +
  '/v7+/v7+/v7+/v7+/v7+/vwAAP+AAP/gAP/wAP/4AP/4AH/8AAf8AAP8AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+AAH+' +
  'AAH+AAH+AAH+AAH/AAD/AAD/wAB//AA//AAf/AAD/AAD/AAf/AA//AB//AD/wAD/AAH/AAH+AAH+AAH+AAH+AAH+AAH+AAH+' +
  'AAH+AAH+AAH+AAH+AAH+AAH+AAP+AAP8AAf8AH/8AP/4AP/4AP/wAP/gAP+AAPwAAADgAAAAB/wAH4AP/wA/gB//gD+AP//A' +
  'P4B//+A/gH//+P+Af4///wD/A///AP4B//4A/gD//gD+AH/8APwAP/gAAAAHwAAB/AAH/wAP/8Af/+A//+B///B/B/j+A/j8' +
  'Afj8APj8APz8APz8APj8Afj+A/h/B/h///A//+Af/+AP/4AH/wAB/AA=';

/** Decode a base64 string to bytes without a DOM or Buffer dependency. */
function b64decode(s: string): Uint8Array {
  const B = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const out = new Uint8Array((s.length * 3) >> 2);
  let o = 0, buf = 0, bits = 0;
  for (let i = 0; i < s.length; i++) {
    const ch = s[i]!;
    if (ch === '=') break;
    buf = (buf << 6) | B.indexOf(ch);
    bits += 6;
    if (bits >= 8) { bits -= 8; out[o++] = (buf >> bits) & 0xff; }
  }
  return out.subarray(0, o);
}

export const BODY: Face = {
  firstChar: 32,
  extra: new Map<number, Glyph>([
    [176, { off: 2021, w: 7, h: 7, advance: 9, bx: 1, by: -15 }],
  ]),
  px: 20,
  ascent: 20,
  descent: 5,
  lineHeight: 25,
  glyphs: BODY_GLYPHS,
  bits: b64decode(BODY_B64),
};

export const VALUE: Face = {
  firstChar: 32,
  extra: new Map<number, Glyph>([
    [176, { off: 17327, w: 22, h: 22, advance: 29, bx: 4, by: -48 }],
  ]),
  px: 64,
  ascent: 62,
  descent: 16,
  lineHeight: 78,
  glyphs: VALUE_GLYPHS,
  bits: b64decode(VALUE_B64),
};

/** Face ids, matching the firmware's font_id_t. */
export const FONT_BODY = 0;
export const FONT_VALUE = 1;
export const FACES: Face[] = [BODY, VALUE];

