#!/usr/bin/env python3
"""Convert the firmware's generated font atlases into a TypeScript module.

WHY GENERATE RATHER THAN RE-RASTERISE: the web app's renderer must produce the SAME BITS as
the firmware, or the live preview on the config page lies about what the panel will show
(NFR-4). Re-running Pillow here would be a second, independent rasteriser — two chances to
disagree about hinting or thresholding, with the golden-image test as the only thing that
would notice. The firmware's atlas headers are already the single source of truth, so this
reads them instead of duplicating the pipeline.

The output is committed (webapp/src/canvas/atlas-data.ts) so a normal `npm test` needs no
C source and no Pillow. Re-run this only when the atlases change:

    python3 firmware/tools/gen_web_atlas.py \
        firmware/lib/layout/src/atlas_body.h firmware/lib/layout/src/atlas_value.h \
        webapp/src/canvas/atlas-data.ts

WHAT IS COPIED: glyph metrics (width, height, advance, bearings) VERBATIM, and the packed
1 bpp bitmaps byte-for-byte. The only change is the container.

BIT ORDER IS DELIBERATELY LEFT AS-IS. In the atlas a SET bit is ink; in the panel framebuffer
a CLEAR bit is black (HW-6). Inverting here would make the two conventions match in the data
and diverge in the renderer's head — the inversion belongs in exactly one place, and that
place is the blitter, where the canvas convention is stated.
"""
import re
import sys


def parse_header(path):
    src = open(path, encoding='utf-8').read()

    def num(name):
        m = re.search(rf'#define\s+{name}\s+(\d+)', src)
        if not m:
            sys.exit(f'{path}: missing #define {name}')
        return int(m.group(1))

    stem = None
    for cand in ('FONT_BODY', 'FONT_VALUE'):
        if f'{cand}_GLYPH_COUNT' in src:
            stem = cand
            break
    if not stem:
        sys.exit(f'{path}: cannot determine the face prefix')

    # The glyph table: { off, w, h, advance, bx, by },
    table = re.search(r'GLYPHS\[[^\]]+\]\s*=\s*\{(.*?)\n\};', src, re.S)
    if not table:
        sys.exit(f'{path}: glyph table not found')
    glyphs = []
    for row in re.finditer(r'\{\s*(\d+)u?,\s*(\d+),\s*(\d+),\s*(\d+),\s*(-?\d+),\s*(-?\d+)\s*\}',
                           table.group(1)):
        glyphs.append(tuple(int(g) for g in row.groups()))

    # The optional non-ASCII table (present when the atlas was generated with --extra).
    extra = []
    em = re.search(r'EXTRA\[[^\]]+\]\s*=\s*\{(.*?)\n\};', src, re.S)
    if em:
        for row in re.finditer(
                r'\{\s*(\d+)u?,\s*(\d+)u?,\s*(\d+),\s*(\d+),\s*(\d+),\s*(-?\d+),\s*(-?\d+)\s*\}',
                em.group(1)):
            cp, off, w, h, adv, bx, by = (int(g) for g in row.groups())
            extra.append((cp, off, w, h, adv, bx, by))

    # The packed bitmap.
    bits_m = re.search(r'BITS\[[^\]]+\]\s*=\s*\{(.*?)\n\};', src, re.S)
    if not bits_m:
        sys.exit(f'{path}: bits array not found')
    bits = [int(v, 16) for v in re.findall(r'0x([0-9A-Fa-f]{2})', bits_m.group(1))]

    expected = num(f'{stem}_GLYPH_COUNT')
    if len(glyphs) != expected:
        sys.exit(f'{path}: parsed {len(glyphs)} glyphs, header says {expected}')

    return {
        'name': 'BODY' if stem == 'FONT_BODY' else 'VALUE',
        'first': num(f'{stem}_FIRST_CHAR'),
        'count': expected,
        'px': num(f'{stem}_PX'),
        'ascent': num(f'{stem}_ASCENT'),
        'descent': num(f'{stem}_DESCENT'),
        'lineHeight': num(f'{stem}_LINE_HEIGHT'),
        'glyphs': glyphs,
        'extra': extra,
        'bits': bits,
    }


def emit(faces, out_path):
    lines = []
    lines.append('/* GENERATED by firmware/tools/gen_web_atlas.py — DO NOT EDIT.')
    lines.append(' *')
    lines.append(' * The firmware\'s own font atlases, as TypeScript. Copied verbatim so the web')
    lines.append(' * renderer cannot disagree with the device about a glyph (NFR-4); see the')
    lines.append(' * generator for why this is a conversion and not a second rasteriser.')
    lines.append(' *')
    lines.append(' * Atlas bit convention: a SET bit is INK. The framebuffer convention is the')
    lines.append(' * opposite (a CLEAR bit is black, HW-6) — the inversion lives in the blitter. */')
    lines.append('')
    lines.append('export interface Glyph {')
    lines.append('  /** Offset into the face\'s bits array. */')
    lines.append('  off: number;')
    lines.append('  w: number;')
    lines.append('  h: number;')
    lines.append('  advance: number;')
    lines.append('  /** Pen-origin to ink-box offset. by is from the BASELINE and negative above it. */')
    lines.append('  bx: number;')
    lines.append('  by: number;')
    lines.append('}')
    lines.append('')
    lines.append('export interface Face {')
    lines.append('  firstChar: number;')
    lines.append('  /** Non-ASCII glyphs, keyed by codepoint. Empty when the face has none. */')
    lines.append('  extra: Map<number, Glyph>;')
    lines.append('  px: number;')
    lines.append('  ascent: number;')
    lines.append('  descent: number;')
    lines.append('  lineHeight: number;')
    lines.append('  glyphs: Glyph[];')
    lines.append('  bits: Uint8Array;')
    lines.append('}')
    lines.append('')

    for f in faces:
        lines.append(f'const {f["name"]}_GLYPHS: Glyph[] = [')
        for (off, w, h, adv, bx, by) in f['glyphs']:
            lines.append(f'  {{ off: {off}, w: {w}, h: {h}, advance: {adv}, bx: {bx}, by: {by} }},')
        lines.append('];')
        lines.append('')

        # Emit as a base64 string and decode at load: a 17,327-byte array literal is ~90 KB
        # of source that the bundler would parse at startup, versus one string decode.
        import base64
        b64 = base64.b64encode(bytes(f['bits'])).decode('ascii')
        chunks = [b64[i:i + 96] for i in range(0, len(b64), 96)]
        lines.append(f'/* {len(f["bits"])} bytes of packed {f["px"]}px glyph data. */')
        lines.append(f'const {f["name"]}_B64 =')
        for i, c in enumerate(chunks):
            end = ';' if i == len(chunks) - 1 else ' +'
            lines.append(f'  \'{c}\'{end}')
        lines.append('')

    lines.append('/** Decode a base64 string to bytes without a DOM or Buffer dependency. */')
    lines.append('function b64decode(s: string): Uint8Array {')
    lines.append('  const B = \'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\';')
    lines.append('  const out = new Uint8Array((s.length * 3) >> 2);')
    lines.append('  let o = 0, buf = 0, bits = 0;')
    lines.append('  for (let i = 0; i < s.length; i++) {')
    lines.append('    const ch = s[i]!;')
    lines.append('    if (ch === \'=\') break;')
    lines.append('    buf = (buf << 6) | B.indexOf(ch);')
    lines.append('    bits += 6;')
    lines.append('    if (bits >= 8) { bits -= 8; out[o++] = (buf >> bits) & 0xff; }')
    lines.append('  }')
    lines.append('  return out.subarray(0, o);')
    lines.append('}')
    lines.append('')

    for f in faces:
        lines.append(f'export const {f["name"]}: Face = {{')
        lines.append(f'  firstChar: {f["first"]},')
        if f['extra']:
            lines.append(f'  extra: new Map<number, Glyph>([')
            for (cp, off, w, h, adv, bx, by) in f['extra']:
                lines.append(f'    [{cp}, {{ off: {off}, w: {w}, h: {h}, advance: {adv}, '
                             f'bx: {bx}, by: {by} }}],')
            lines.append('  ]),')
        else:
            lines.append('  extra: new Map(),')
        lines.append(f'  px: {f["px"]},')
        lines.append(f'  ascent: {f["ascent"]},')
        lines.append(f'  descent: {f["descent"]},')
        lines.append(f'  lineHeight: {f["lineHeight"]},')
        lines.append(f'  glyphs: {f["name"]}_GLYPHS,')
        lines.append(f'  bits: b64decode({f["name"]}_B64),')
        lines.append('};')
        lines.append('')

    lines.append('/** Face ids, matching the firmware\'s font_id_t. */')
    lines.append('export const FONT_BODY = 0;')
    lines.append('export const FONT_VALUE = 1;')
    lines.append('export const FACES: Face[] = [BODY, VALUE];')
    lines.append('')

    open(out_path, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print(f'wrote {out_path}')


if __name__ == '__main__':
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    faces = [parse_header(sys.argv[1]), parse_header(sys.argv[2])]
    emit(faces, sys.argv[3])
