#!/usr/bin/env python3
"""Emit firmware/tools/golden/default_layout.h from the web app's layout fixture.

WHY A GENERATOR AND NOT A HAND-WRITTEN HEADER: the golden image is a cross-check between two
renderers in two languages (NFR-4). If the C header and the JSON fixture are maintained
separately they WILL drift, and the drift is invisible — the web app would compare its output
against a golden built from a layout it is not rendering, and the test would either pass
meaninglessly or fail for a reason that is not a bug. Generating the header from the same JSON
the web app consumes removes the second copy.

Usage:
    python3 firmware/tools/gen_default_layout_h.py <fixture.json> <out.h>
"""

import json
import sys

ALIGN_H = {'L', 'C', 'R'}
ALIGN_V = {'T', 'M', 'B'}


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, out = sys.argv[1], sys.argv[2]
    d = json.load(open(src))

    labels = d['labels']
    rules = d['rules']
    fields = d['fields']

    for f in fields:
        if f['alignH'] not in ALIGN_H or f['alignV'] not in ALIGN_V:
            sys.exit(f'field {f}: bad alignment')
        if not (0 <= f['x'] and 0 <= f['y'] and f['x'] + f['w'] <= 920 and f['y'] + f['h'] <= 680):
            sys.exit(f'field {f}: outside the panel')

    L = []
    L.append('#pragma once')
    L.append('')
    L.append('/* GENERATED by tools/gen_default_layout_h.py from the web app\'s layout fixture.')
    L.append(' * DO NOT EDIT — regenerate instead. See that script for why there is no second')
    L.append(' * hand-maintained copy of this layout. */')
    L.append('')
    L.append('#include "canvas.h"')
    L.append('#include "render.h"')
    L.append('#include "fonts.h"')
    L.append('')
    L.append('/* Labels and chrome the web app bakes into the static layer. */')
    L.append('typedef struct {')
    L.append('    int x, y;')
    L.append('    const char *text;')
    L.append('    int font_id;')
    L.append('} static_label_t;')
    L.append('')
    L.append(f'#define GOLDEN_LABEL_COUNT {len(labels)}')
    L.append('static const static_label_t GOLDEN_LABELS[GOLDEN_LABEL_COUNT] = {')
    for l in labels:
        L.append(f'    {{ {l["x"]:4d}, {l["y"]:4d}, "{l["text"]}", FONT_'
                 f'{"VALUE" if l["font"] else "BODY"} }},')
    L.append('};')
    L.append('')
    L.append('/* Dividers: y, thickness, inset from each edge. */')
    L.append('typedef struct { int y, thickness, inset; } static_rule_t;')
    L.append('')
    L.append(f'#define GOLDEN_RULE_COUNT {len(rules)}')
    L.append('static const static_rule_t GOLDEN_RULES[GOLDEN_RULE_COUNT] = {')
    for r in rules:
        L.append(f'    {{ {r["y"]}, {r["thickness"]}, {r["inset"]} }},')
    L.append('};')
    L.append('')
    L.append('/* The dynamic value boxes the firmware stamps. */')
    L.append(f'#define GOLDEN_FIELD_COUNT {len(fields)}')
    L.append('static const value_field_t GOLDEN_FIELDS[GOLDEN_FIELD_COUNT] = {')
    for f in fields:
        L.append(f'    {{ .x = {f["x"]}, .y = {f["y"]}, .w = {f["w"]}, .h = {f["h"]}, '
                 f'.align_h = \'{f["alignH"]}\', .align_v = \'{f["alignV"]}\', '
                 f'.font_id = FONT_{"VALUE" if f["font"] else "BODY"}, '
                 f'.kind = {"VALUE_KIND_ICON" if f.get("kind") == "i" else "VALUE_KIND_TEXT"} }},')
    L.append('};')
    L.append('')
    L.append('static const char *const GOLDEN_VALUES[GOLDEN_FIELD_COUNT] = {')
    L.append('    ' + ', '.join(f'"{f["sample"]}"' for f in fields) + ',')
    L.append('};')
    L.append('')
    L.append('/* Build the static layer the web app is expected to push: white, with labels and')
    L.append(' * rules. Labels go through the renderer itself, which is the same path the device')
    L.append(' * uses for a value — so a label and a reading cannot be placed differently. */')
    L.append('static inline void golden_build_static_layer(uint8_t *fb)')
    L.append('{')
    L.append('    canvas_t c;')
    L.append('    canvas_init(&c, fb);')
    L.append('    canvas_fill(&c, 0);          /* white */')
    L.append('')
    L.append('    for (int i = 0; i < GOLDEN_LABEL_COUNT; i++) {')
    L.append('        const static_label_t *l = &GOLDEN_LABELS[i];')
    L.append('        value_field_t f = { .x = l->x, .y = l->y, .w = 500, .h = 40,')
    L.append('                            .align_h = \'L\', .align_v = \'T\', .font_id = l->font_id };')
    L.append('        const char *v[1] = { l->text };')
    L.append('        render_compose(&c, fb, &f, v, 1);')
    L.append('    }')
    L.append('')
    L.append('    for (int i = 0; i < GOLDEN_RULE_COUNT; i++) {')
    L.append('        for (int t = 0; t < GOLDEN_RULES[i].thickness; t++) {')
    L.append('            for (int x = GOLDEN_RULES[i].inset; x < EPD_WIDTH - GOLDEN_RULES[i].inset; x++) {')
    L.append('                canvas_set_px(&c, x, GOLDEN_RULES[i].y + t, 1);')
    L.append('            }')
    L.append('        }')
    L.append('    }')
    L.append('}')
    L.append('')

    open(out, 'w').write('\n'.join(L))
    print(f'wrote {out}: {len(labels)} labels, {len(rules)} rules, {len(fields)} fields')


if __name__ == '__main__':
    main()
