#!/usr/bin/env python3
"""Generate the QR matrices the provisioning screen draws, as a C header.

WHY THE MATRICES ARE PRE-GENERATED RATHER THAN ENCODED ON THE DEVICE: all three codes are
FIXED URLs — the setup page address (the AP is always 192.168.4.1) and the two app-store
listings. Nothing about them varies from device to device, so a QR encoder on the target would
be several hundred lines of Reed-Solomon and masking logic that could only ever produce one of
three known outputs. Generating them here with a well-tested library (`qrcode`) removes that
entire class of bug from the firmware and costs a few hundred bytes of flash.

This is the same principle as the font atlases: compute what is constant at build time, ship
the result, and keep the device's code small enough to be obviously correct.

Run from firmware/:  python3 tools/gen_qr.py
Output:              lib/provscreen/src/qr_data.h
"""

import os
import sys

try:
    import qrcode
except ImportError:
    sys.exit("qrcode is required: python3 -m pip install qrcode")

# The three codes and the symbols the C side refers to them by.
CODES = [
    ("QR_PORTAL",  "http://192.168.4.1/",
     "The setup page. The AP's address is fixed, so this URL never varies."),
    ("QR_IOS",     "https://apps.apple.com/app/id1474040630",
     "ESP SoftAP Provisioning, App Store. Verified: the listing resolves (HTTP 200). This is "
     "the app the auto-setup code targets, because it is the one that can show a network list "
     "AND the one that can be reached by QR on iOS (its device SEARCH is unsupported on iOS, so "
     "a code is the only way in there)."),
    ("QR_ANDROID", "https://play.google.com/store/apps/details?id=com.espressif.provsoftap",
     "ESP SoftAP Provisioning, Google Play. Verified: the listing resolves (HTTP 200)."),
]

OUT = os.path.join(os.path.dirname(__file__), "..", "lib", "provscreen", "src", "qr_data.h")

# Error correction L: plenty for a code displayed on a clean glass panel at close range, and it
# keeps the matrix small — every extra level adds modules, which costs screen area the
# instructions also need. There is no printing or wrinkling here to correct for.
ECC = qrcode.constants.ERROR_CORRECT_L
BORDER = 4      # the standard quiet zone, in modules. A code without it will not scan.


def pack(matrix):
    """Row-major, MSB-first, one bit per module — the same bit convention the display uses,
    so the blitter is a straight copy. Returns (size, packed_bytes)."""
    size = len(matrix)
    pitch = (size + 7) // 8
    out = bytearray(pitch * size)
    for y, row in enumerate(matrix):
        for x, cell in enumerate(row):
            if cell:
                out[y * pitch + (x >> 3)] |= 0x80 >> (x & 7)
    return size, pitch, bytes(out)


def main():
    lines = [
        "/* GENERATED by tools/gen_qr.py — do not edit by hand.",
        " *",
        " * QR matrices for the provisioning screen, packed 1 bit per module, row-major,",
        " * MSB-first. See the generator for why these are pre-computed rather than encoded",
        " * on the device.",
        " */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    int      size;    /* modules per side, excluding the quiet zone */",
        "    int      pitch;   /* bytes per row = (size + 7) / 8 */",
        "    const uint8_t *bits;",
        "} qr_code_t;",
        "",
    ]

    table = []
    for name, url, note in CODES:
        q = qrcode.QRCode(error_correction=ECC, border=BORDER, box_size=1)
        q.add_data(url)
        q.make(fit=True)
        m = q.get_matrix()
        size, pitch, data = pack(m)
        table.append(name)
        lines.append(f"/* {note}")
        lines.append(f" * {url!r} */")
        lines.append(f"static const uint8_t {name}_bits[{len(data)}] = {{")
        for i in range(0, len(data), 12):
            lines.append("    " + ",".join("0x%02X" % b for b in data[i:i + 12]) + ",")
        lines.append("};")
        lines.append(f"static const qr_code_t {name} = {{ {size}, {pitch}, {name}_bits }};")
        lines.append("")
        print(f"{name}: {url}  ({size}x{size}, {len(data)} bytes)")

    lines.append("static const qr_code_t *const PROV_QR_CODES[] = { "
                 + ", ".join(f"&{n}" for n in table) + " };")
    lines.append("enum { PROV_QR_COUNT = " + str(len(table)) + " };")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
