#!/usr/bin/env python3
"""Generate the boot splash from the OETSolutions / Aether logo.

WHY THIS IS A GENERATOR AND NOT A COMMITTED BINARY: the source is a 1254x1254 RGBA PNG with
large transparent margins. Committing the derived 1bpp array alone would mean nobody could see
where it came from or regenerate it if the artwork changes; committing the source would put a
1 MB file in the repo for one asset. The generator keeps both out: point it at the source PNG
and it reproduces the asset, and the committed output is only the bytes the panel needs.

It trims the transparent dead space, scales the artwork to sit centred on the panel with a
margin, and thresholds to 1 bit. The threshold is deliberately near the middle of the observed
ink luminance range (52..111) and is not gamma-corrected: the art is dark grey and the panel is
1 bit, so anything between the floor and the ink reads as black and the edge stays smooth.

Run from firmware/:  python3 tools/gen_boot_logo.py <logo.png>
Output:              src/boot_logo_data.c
"""

import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: python3 -m pip install Pillow")

PANEL_W, PANEL_H = 920, 680
MARGIN = 70          # keeps the mark clear of the bezel edge
THRESHOLD = 190      # alpha-normalised: below this is ink. See the note above.

DEFAULT_SRC = ("/Users/cbrown/Library/CloudStorage/GoogleDrive-cbrown350@gmail.com/"
               "My Drive/oetsolutions.com/OETSolutions-Aether Combined Logo.png")


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    im = Image.open(src).convert("RGBA")

    # ---- Trim the transparent dead space ----
    # The source is 1254x1254 with the artwork occupying a thin horizontal band, so without
    # this the logo would render tiny in the middle of a mostly-empty frame.
    #
    # The bbox is computed from alpha > 32 rather than Image.getbbox(): getbbox() counts ANY
    # non-zero alpha, and this artwork has faint anti-aliased haze hundreds of pixels into the
    # margins. Trusting getbbox() left the trim almost as tall as the original (1191 of 1254),
    # so the logo then scaled down to fit that phantom height and rendered far smaller than it
    # should. Measured content is a 679-row band, not 1191.
    alpha = im.split()[3]
    boxes = ((alpha.point(lambda v: 255 if v > 32 else 0)).getbbox())
    if boxes is None:
        sys.exit("the source image is fully transparent")
    im = im.crop(boxes)
    print(f"trimmed to {im.size} (was {Image.open(src).size})")

    # ---- Scale to fit inside the panel, preserving aspect ratio ----
    avail_w = PANEL_W - 2 * MARGIN
    avail_h = PANEL_H - 2 * MARGIN
    scale = min(avail_w / im.width, avail_h / im.height)
    new_w = max(1, int(im.width * scale))
    new_h = max(1, int(im.height * scale))
    im = im.resize((new_w, new_h), Image.LANCZOS)
    print(f"scaled to {im.size} (fit factor {scale:.3f})")

    # ---- Composite onto white and threshold ----
    # White page, not black: the panel's resting state is white and the splash should look like
    # a printed mark, not an inverted plate.
    page = Image.new("RGBA", (PANEL_W, PANEL_H), (255, 255, 255, 255))
    page.alpha_composite(im, ((PANEL_W - new_w) // 2, (PANEL_H - new_h) // 2))
    grey = page.convert("L")

    # 1bpp, MSB-first, row-major, bit SET = white — the framebuffer convention (HW-6).
    out = bytearray(PANEL_W // 8 * PANEL_H)
    px = grey.load()
    ink = 0
    for y in range(PANEL_H):
        row = y * (PANEL_W // 8)
        for x in range(PANEL_W):
            if px[x, y] < THRESHOLD:
                out[row + (x >> 3)] &= ~(0x80 >> (x & 7))   # clear bit = black ink
                ink += 1
            else:
                out[row + (x >> 3)] |= (0x80 >> (x & 7))
    total = PANEL_W * PANEL_H
    print(f"ink coverage {ink / total:.1%} of the panel")

    # ---- Emit ----
    lines = [
        "/* GENERATED by tools/gen_boot_logo.py — do not edit by hand.",
        " *",
        " * The OETSolutions / Aether boot mark, trimmed, scaled and thresholded to 1bpp in the",
        " * panel's framebuffer convention (MSB-first, row-major, bit SET = white). See the",
        " * generator for the pipeline and why the asset is derived rather than committed raw.",
        " */",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        f"const uint8_t boot_logo[{len(out)}] = {{",
    ]
    for i in range(0, len(out), 16):
        lines.append("    " + ",".join("0x%02X" % b for b in out[i:i + 16]) + ",")
    lines.append("};")
    lines.append("const size_t boot_logo_len = sizeof(boot_logo);")
    lines.append("")

    with open("src/boot_logo_data.c", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote src/boot_logo_data.c")


if __name__ == "__main__":
    main()
