/**
 * The JS formatter must reproduce C's `printf("%.*f")` EXACTLY.
 *
 * WHY THIS IS NOT PEDANTRY. The device draws every reading through printf; the editor previews it
 * through this module. Wherever the two disagree, the preview is a confident lie about the one thing
 * it exists to show — the number that will be on the wall. Two disagreements were real:
 *
 *   1. ROUNDING MODE. printf rounds a half to EVEN, `toFixed` rounds a half AWAY FROM ZERO. A tie is
 *      ordinary here — 72.5 °F at zero decimals — and printf draws "72" where toFixed gives "73".
 *   2. SCALING LOSS. `0.05 * 10` is exactly 0.5 in binary floating point, so rounding a scaled value
 *      cannot tell "exactly 0.05" from "a hair above it" and rounds DOWN where printf rounds up.
 *
 * The fixture is generated by running printf itself (scripts/gen-printf-fixture.py), so the expected
 * strings are the platform's own answer rather than a second guess at the rule.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { fixedToEven, formatValue } from '../src/data/format';

const here = dirname(fileURLToPath(import.meta.url));
const rows = JSON.parse(
  readFileSync(resolve(here, 'fixtures/printf-fixed.json'), 'utf8'),
) as { value: number; decimals: number; negzero: number; out: string }[];

/**
 * The row's value as a double, with negative zero restored.
 *
 * JSON has no -0: `JSON.stringify(-0)` is "0" and `JSON.parse("-0")` gives +0, so the sign of an
 * exactly-negative-zero row would be lost on the way to the test. The fixture records it in a
 * separate `negzero` field (from C's signbit) precisely because the formatter must print "-0.0"
 * there, and a fixture that silently became +0 would make the test assert the wrong answer.
 */
function valueOf(r: { value: number; negzero: number }): number {
  return r.negzero && r.value === 0 ? -0 : r.value;
}

describe('fixedToEven matches printf', () => {
  it('has a fixture with real coverage', () => {
    expect(rows.length).toBeGreaterThan(300);
  });

  it('reproduces every printf result', () => {
    const bad: string[] = [];
    for (const r of rows) {
      const got = fixedToEven(valueOf(r), r.decimals);
      if (got !== r.out) bad.push(`printf("%.*f", ${r.value}) = ${JSON.stringify(r.out)}, got ${JSON.stringify(got)}`);
    }
    expect(bad).toEqual([]);
  });
});

describe('the rounding cases that actually differ', () => {
  /* These are the reported-class bugs, named so a regression says WHAT broke rather than only that
   * the fixture moved. */
  it('rounds a tie to even, like printf', () => {
    /* The one a weather display hits: 72.5 °F is an exact tie at zero decimals. */
    expect(fixedToEven(72.5, 0)).toBe('72');
    expect(fixedToEven(0.5, 0)).toBe('0');
    expect(fixedToEven(1.5, 0)).toBe('2');
    expect(fixedToEven(2.5, 0)).toBe('2');
    expect(fixedToEven(3.5, 0)).toBe('4');
  });

  it('rounds a value just off a boundary UP, not down', () => {
    /* The scaling implementation failed here: 0.05 is a hair above 0.05 in binary, and 0.05*10 is
     * exactly 0.5, so a naive scale-and-round lost the distinction and produced 0.0 where printf
     * produces 0.1. */
    expect(fixedToEven(0.05, 1)).toBe('0.1');
    expect(fixedToEven(68.45, 1)).toBe('68.5');
    expect(fixedToEven(12.345, 2)).toBe('12.35');
  });

  it('keeps the sign on a negative that rounds to zero', () => {
    /* printf writes "-0", not "0": -0.4 °F is below freezing, so the sign is information. */
    expect(fixedToEven(-0.05, 0)).toBe('-0');
    expect(fixedToEven(-0.05, 1)).toBe('-0.1');
    expect(fixedToEven(-0.4, 0)).toBe('-0');
// eslint-disable-next-line no-irregular-whitespace
  });

  it('keeps a negative zero negative', () => {
    /* `-0 < 0` is false, so only Object.is sees it — and printf prints "-0.0". */
    expect(fixedToEven(-0, 1)).toBe('-0.0');
    expect(fixedToEven(0, 1)).toBe('0.0');
  });

  it('never uses exponential notation for a large reading', () => {
    expect(fixedToEven(123456.789, 2)).toBe('123456.79');
    expect(fixedToEven(1e-7, 6)).toBe('0.000000');
  });
});

describe('formatValue composes affixes around the number', () => {
  it('puts a prefix and suffix around the body', () => {
    expect(formatValue({ value: 3, status: 'ok' }, { decimals: 0, prefix: 'layers ' })).toBe('layers 3');
    expect(formatValue({ value: 68.4, status: 'ok' }, { decimals: 1, suffix: '°F' })).toBe('68.4°F');
  });

  it('falls back instead of printing a non-number', () => {
    expect(formatValue({ value: NaN, status: 'ok' }, { fallback: '--' })).toBe('--');
    expect(formatValue({ value: 0, status: 'unavailable' }, { fallback: '--' })).toBe('--');
  });
});
