#pragma once

/* GENERATED by tools/gen_default_layout_h.py from the web app's layout fixture.
 * DO NOT EDIT — regenerate instead. See that script for why there is no second
 * hand-maintained copy of this layout. */

#include "canvas.h"
#include "render.h"
#include "fonts.h"

/* Labels and chrome the web app bakes into the static layer. */
typedef struct {
    int x, y;
    const char *text;
    int font_id;
} static_label_t;

#define GOLDEN_LABEL_COUNT 7
static const static_label_t GOLDEN_LABELS[GOLDEN_LABEL_COUNT] = {
    {   40,   32, "NOW", FONT_20 },
    {  440,   32, "HALLWAY", FONT_20 },
    {  680,   32, "TODAY HIGH", FONT_20 },
    {  440,  164, "OUTDOOR", FONT_20 },
    {  680,  164, "TODAY LOW", FONT_20 },
    {  680,  296, "TOMORROW HIGH", FONT_20 },
    {   40,  308, "LOCATION", FONT_20 },
};

/* Dividers: y, thickness, inset from each edge. */
typedef struct { int y, thickness, inset; } static_rule_t;

#define GOLDEN_RULE_COUNT 2
static const static_rule_t GOLDEN_RULES[GOLDEN_RULE_COUNT] = {
    { 140, 2, 40 },
    { 440, 2, 40 },
};

/* The dynamic value boxes the firmware stamps. */
#define GOLDEN_FIELD_COUNT 11
static const value_field_t GOLDEN_FIELDS[GOLDEN_FIELD_COUNT] = {
    { .x = 40, .y = 64, .w = 360, .h = 120, .align_h = 'L', .align_v = 'T', .font_id = FONT_64, .kind = VALUE_KIND_TEXT },
    { .x = 40, .y = 196, .w = 360, .h = 50, .align_h = 'L', .align_v = 'T', .font_id = FONT_20, .kind = VALUE_KIND_TEXT },
    { .x = 40, .y = 258, .w = 200, .h = 50, .align_h = 'L', .align_v = 'T', .font_id = FONT_20, .kind = VALUE_KIND_TEXT },
    { .x = 268, .y = 258, .w = 62, .h = 62, .align_h = 'L', .align_v = 'T', .font_id = FONT_20, .kind = VALUE_KIND_ICON },
    { .x = 40, .y = 340, .w = 360, .h = 44, .align_h = 'L', .align_v = 'T', .font_id = FONT_20, .kind = VALUE_KIND_TEXT },
    { .x = 440, .y = 64, .w = 200, .h = 90, .align_h = 'L', .align_v = 'T', .font_id = FONT_20, .kind = VALUE_KIND_TEXT },
    { .x = 440, .y = 196, .w = 200, .h = 90, .align_h = 'L', .align_v = 'T', .font_id = FONT_20, .kind = VALUE_KIND_TEXT },
    { .x = 680, .y = 64, .w = 200, .h = 90, .align_h = 'L', .align_v = 'T', .font_id = FONT_20, .kind = VALUE_KIND_TEXT },
    { .x = 680, .y = 196, .w = 200, .h = 90, .align_h = 'L', .align_v = 'T', .font_id = FONT_20, .kind = VALUE_KIND_TEXT },
    { .x = 680, .y = 328, .w = 200, .h = 90, .align_h = 'L', .align_v = 'T', .font_id = FONT_20, .kind = VALUE_KIND_TEXT },
    { .x = 40, .y = 452, .w = 840, .h = 80, .align_h = 'L', .align_v = 'M', .font_id = FONT_20, .kind = VALUE_KIND_TEXT },
};

static const char *const GOLDEN_VALUES[GOLDEN_FIELD_COUNT] = {
    "68.4", "68.4", "68.4", "04d", "68.4", "68.4", "68.4", "68.4", "68.4", "68.4", "68.4",
};

/* Build the static layer the web app is expected to push: white, with labels and
 * rules. Labels go through the renderer itself, which is the same path the device
 * uses for a value — so a label and a reading cannot be placed differently. */
static inline void golden_build_static_layer(uint8_t *fb)
{
    canvas_t c;
    canvas_init(&c, fb);
    canvas_fill(&c, 0);          /* white */

    for (int i = 0; i < GOLDEN_LABEL_COUNT; i++) {
        const static_label_t *l = &GOLDEN_LABELS[i];
        value_field_t f = { .x = l->x, .y = l->y, .w = 500, .h = 40,
                            .align_h = 'L', .align_v = 'T', .font_id = l->font_id };
        const char *v[1] = { l->text };
        render_compose(&c, fb, &f, v, 1);
    }

    for (int i = 0; i < GOLDEN_RULE_COUNT; i++) {
        for (int t = 0; t < GOLDEN_RULES[i].thickness; t++) {
            for (int x = GOLDEN_RULES[i].inset; x < EPD_WIDTH - GOLDEN_RULES[i].inset; x++) {
                canvas_set_px(&c, x, GOLDEN_RULES[i].y + t, 1);
            }
        }
    }
}
