#pragma once
#include <stdint.h>

/* The rasterised font LADDER (FR-4a). Generated by tools/gen_font_atlas.py — see that file
 * for why the panel uses pre-rendered atlases rather than a runtime font engine, and why the
 * ladder stops at 128 px.
 *
 * THE LADDER IS DATA, NOT TYPES. The first cut shipped two faces, each with its own glyph
 * struct and its own pair of read/find functions in fonts.c; adding a size meant editing the C
 * glue, so only two ever existed. The generator now emits EVERY face with ONE struct shape and
 * this one X-macro list of sizes, and both the enum below and the ATLAS_FACES table are built
 * from that list — so a size in the ladder is automatically a usable face everywhere.
 *
 * Glyphs are 1 bpp, MSB-first, row-major, pitch = (w + 7) / 8, with WHITE padding in the final
 * partial byte, so a blitter can copy whole bytes without masking.
 *
 * This includes atlas_ladder.h (the sizes, counts and structs), NOT atlas.h (the ~170 KB of
 * bitmap). The data is included by fonts.c alone; see atlas_ladder.h for why. */
#include "atlas_ladder.h"

/* FONT_16, FONT_20, ... FONT_128 — one enum value per ladder entry, in ascending order, with
 * the numeric value equal to the index into ATLAS_FACES. Built from the generated list so the
 * two cannot fall out of step; a size added to the generator appears here with no edit. */
#define FONT_ENUM_ENTRY(px) FONT_##px,
typedef enum {
    ATLAS_LADDER(FONT_ENUM_ENTRY)
    FONT_COUNT
} font_id_t;
#undef FONT_ENUM_ENTRY

/* The two faces most call sites want by ROLE rather than by size: the body face and the hero
 * value face. Aliases, not separate faces — so "give me the value face" keeps meaning the same
 * thing after the ladder changes, and the value face stays the ~64 px one the layout was tuned
 * against. Callers that want a specific size use FONT_<px> directly. */
#define FONT_BODY  FONT_20
#define FONT_VALUE FONT_64

/* Look up one glyph. Returns 0 on success, negative if the char has no glyph.
 *
 * `*bits` points at `(*h) * ceil(*w/8)` bytes. For a blank glyph (space) `*w` and `*h` are
 * 0 and `*bits` may be NULL — the advance is still non-zero, so callers must use the
 * advance for spacing and not the width. */
int font_glyph(font_id_t font, char ch, const uint8_t **bits, int *w, int *h);

/* ---- codepoint API ----
 *
 * WHY THIS EXISTS IN ADDITION TO THE char API: `char ch` is ONE byte, so it cannot carry a
 * multi-byte character. The degree sign is U+00B0 = two bytes, and a caller that decodes a
 * string one character at a time (as the renderer must) has a codepoint, not a byte. Passing
 * just the lead byte to the char API made font_glyph() look at the NEXT byte in memory for a
 * continuation, find a non-continuation, and fail — so the glyph existed in the atlas and the
 * renderer still drew nothing.
 *
 * A renderer should use these. The char API remains for ASCII-only callers and is a thin
 * wrapper over font_utf8_next(). */
unsigned font_utf8_next(const char **p);
int font_glyph_cp(font_id_t font, unsigned codepoint, const uint8_t **bits, int *w, int *h);
int font_advance_cp(font_id_t font, unsigned codepoint);
int font_bearing_cp(font_id_t font, unsigned codepoint, int *bx, int *by);

/* Advance width of one character, in pixels. Never 0 for printable ASCII. */
int font_advance(font_id_t font, char ch);

/* Offset from the pen origin to the glyph's ink box top-left, in pixels. Both are SIGNED.
 *
 * `by` is relative to the BASELINE and is NEGATIVE for ink above it, so a digit has
 * by + h == 0 and a descender has by + h > 0. This convention matters: an
 * ascender-relative value looks equally plausible but pushes every digit a full ascent
 * down the line, clipping the value face in half.
 *
 * A renderer that placed glyphs by their ink box alone would float a '.' at the top of the
 * line instead of on the baseline. Returns 0 on success, negative if the char has no glyph. */
int font_bearing(font_id_t font, char ch, int *bx, int *by);

/* Advance height of the face: the line box, for vertical placement. */
int font_line_height(font_id_t font);

/* Measure a string. `*w` is the sum of advances; `*h` is the face's line height (NOT the
 * tallest glyph's ink height) so that a line containing "T" and one containing "g" have
 * the same measured height and text does not jitter between refreshes. Returns 0 on
 * success, negative if any character has no glyph. */
int font_measure(font_id_t font, const char *s, int *w, int *h);

/* Cap height and baseline offset from the top of the line box, in pixels. Needed to align
 * a big value face against a body-face label on the same baseline. */
int font_ascent(font_id_t font);
int font_descent(font_id_t font);

/* The pixel size of a face, so a caller can pick the nearest ladder entry to a requested size.
 * Returns 0 for an out-of-range id. */
int font_px(font_id_t font);

/* THE NEAREST LADDER FACE to a requested pixel size. This is the ONE place a free-form size is
 * resolved into a real face, on the device; the web app has its own copy of the rule and the
 * golden test keeps the two honest.
 *
 * The rule is NEAREST, not "big is big": the old two-face version used a threshold at 48 px, so
 * every size at or above 48 snapped to 64 and 40 selected 20 — a user who asked for 48 got a
 * face 33% larger than requested. Nearest picks the face whose px is closest in RATIO (which is
 * what the eye reads), ties going to the SMALLER face: an oversized reading overflows its box
 * and is clipped, which looks broken, while an undersized one is merely quiet. */
font_id_t font_face_for_px(double px);
