#pragma once
#include <stdint.h>

/* Rasterised font atlases (FR-4a). Generated by tools/gen_font_atlas.py — see that file
 * for why atlases and not a runtime font engine.
 *
 * Glyphs are 1 bpp, MSB-first, row-major, with pitch = (w + 7) / 8 and WHITE padding in the
 * final partial byte, so a blitter can copy whole bytes without masking. */

typedef enum {
    FONT_BODY = 0,      /* ~20 px: labels, units, timestamps */
    FONT_VALUE,         /* ~64 px: the hero numerals */
    FONT_COUNT
} font_id_t;

/* Look up one glyph. Returns 0 on success, negative if the char has no glyph.
 *
 * `*bits` points at `(*h) * ceil(*w/8)` bytes. For a blank glyph (space) `*w` and `*h` are
 * 0 and `*bits` may be NULL — the advance is still non-zero, so callers must use the
 * advance for spacing and not the width. */
int font_glyph(font_id_t font, char ch, const uint8_t **bits, int *w, int *h);

/* ---- codepoint API ----
 *
 * WHY THIS EXISTS IN ADDITION TO THE char API: `char ch` is ONE byte, so it cannot carry a
 * multi-byte character. The degree sign is U+00B0 = two bytes, and a caller that decodes a
 * string one character at a time (as the renderer must) has a codepoint, not a byte. Passing
 * just the lead byte to the char API made font_glyph() look at the NEXT byte in memory for a
 * continuation, find a non-continuation, and fail — so the glyph existed in the atlas and the
 * renderer still drew nothing.
 *
 * A renderer should use these. The char API remains for ASCII-only callers and is a thin
 * wrapper over font_utf8_next(). */
unsigned font_utf8_next(const char **p);
int font_glyph_cp(font_id_t font, unsigned codepoint, const uint8_t **bits, int *w, int *h);
int font_advance_cp(font_id_t font, unsigned codepoint);
int font_bearing_cp(font_id_t font, unsigned codepoint, int *bx, int *by);

/* Advance width of one character, in pixels. Never 0 for printable ASCII. */
int font_advance(font_id_t font, char ch);

/* Offset from the pen origin to the glyph's ink box top-left, in pixels. Both are SIGNED.
 *
 * `by` is relative to the BASELINE and is NEGATIVE for ink above it, so a digit has
 * by + h == 0 and a descender has by + h > 0. This convention matters: an
 * ascender-relative value looks equally plausible but pushes every digit a full ascent
 * down the line, clipping the value face in half.
 *
 * A renderer that placed glyphs by their ink box alone would float a '.' at the top of the
 * line instead of on the baseline. Returns 0 on success, negative if the char has no glyph. */
int font_bearing(font_id_t font, char ch, int *bx, int *by);

/* Advance height of the face: the line box, for vertical placement. */
int font_line_height(font_id_t font);

/* Measure a string. `*w` is the sum of advances; `*h` is the face's line height (NOT the
 * tallest glyph's ink height) so that a line containing "T" and one containing "g" have
 * the same measured height and text does not jitter between refreshes. Returns 0 on
 * success, negative if any character has no glyph. */
int font_measure(font_id_t font, const char *s, int *w, int *h);

/* Cap height and baseline offset from the top of the line box, in pixels. Needed to align
 * a big value face against a body-face label on the same baseline. */
int font_ascent(font_id_t font);
int font_descent(font_id_t font);
