#pragma once
#include <stdint.h>
#include <stddef.h>

/* A weather condition icon: a 1 bpp bitmap in the ATLAS convention (a SET bit is ink), so it
 * blits over the static layer like a glyph and never punches a white box through the layout. */
typedef struct {
    int             w, h;
    const uint8_t  *bits;   /* (h) * ((w + 7) / 8) bytes */
} weather_icon_t;

/* The icon set, in the order weather_icon_index() returns. The array itself is generated by
 * tools/gen_weather_icons.py; this header is the contract between the generator, the mapping
 * below and the renderer, so all three agree on the index space. */
#define WEATHER_ICON_COUNT 9

/* The indices, named. The numeric order MUST match the generator's ICONS list. */
enum {
    WEATHER_ICON_CLEAR        = 0,   /* OWM 01d */
    WEATHER_ICON_CLEAR_NIGHT  = 1,   /* OWM 01n */
    WEATHER_ICON_PARTLY       = 2,   /* OWM 02d */
    WEATHER_ICON_PARTLY_NIGHT = 3,   /* OWM 02n */
    WEATHER_ICON_CLOUDY       = 4,   /* OWM 03d/03n/04d/04n */
    WEATHER_ICON_RAIN         = 5,   /* OWM 09d/09n/10d/10n */
    WEATHER_ICON_STORM        = 6,   /* OWM 11d/11n */
    WEATHER_ICON_SNOW         = 7,   /* OWM 13d/13n */
    WEATHER_ICON_FOG          = 8,   /* OWM 50d/50n */
    WEATHER_ICON_UNKNOWN      = -1   /* no usable code */
};

extern const weather_icon_t weather_icons[WEATHER_ICON_COUNT];

/* Map an OpenWeatherMap icon code to one of the above.
 *
 * THE CODE IS TWO DIGITS AND A d/n LETTER ("04n"), and BOTH parts are used. The two digits
 * select the condition; the letter selects day or night for the two conditions that actually
 * look different after dark — clear and partly-cloudy. The rest collapse to one icon per
 * condition because a rained-on cloud looks the same at midnight. Treating the letter as
 * meaningful only there is what keeps the set to nine icons instead of eighteen without ever
 * showing a sun on the glass at 2 a.m.
 *
 * The mapping is by a RANGE TEST on the parsed number rather than a lookup of nineteen literal
 * strings: OWM only ever emits 01..50 in the documented steps, and a switch on two characters
 * is the kind of thing that quietly misses a code the API adds later. Anything unparseable or
 * outside the known groups returns WEATHER_ICON_UNKNOWN, which the renderer draws as its text
 * fallback rather than as a wrong-weather icon — an invented icon is worse than a missing one.
 *
 * PURE and host-tested (test/test_weather_icons): the caller passes the code string, so no
 * cJSON or HTTP is involved and the whole mapping is verifiable off-device. */
int weather_icon_index(const char *code);
