#!/usr/bin/env python3
"""Capture real OpenWeatherMap responses and regenerate the C fixtures in
firmware/test/test_owm_real/.

Real data is the point: a hand-written fixture cannot contain the surprises a live
response does. Capturing it found that 37 of 40 forecast blocks report
temp_min == temp_max, and that the first block is 00:00 local (so a UTC grouping would
shift every day index by one).

Usage:
    python3 tools/gen_owm_fixture.py                 # uses OWM_API_KEY from code/.env
    python3 tools/gen_owm_fixture.py --lat 41.1 --lon -112.0

The key is read from code/.env and never written to the generated headers.
"""
import argparse, json, os, re, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "firmware", "test", "test_owm_real")

BASE = "https://api.openweathermap.org/data/2.5"


def read_key():
    env = os.path.join(ROOT, ".env")
    if not os.path.exists(env):
        sys.exit(f"no {env}; set OWM_API_KEY there")
    m = re.search(r"OWM_API_KEY\s*=\s*(\S+)", open(env).read())
    if not m:
        sys.exit("OWM_API_KEY not found in .env")
    return m.group(1).strip().strip('"').strip("'")


def fetch(path, params):
    url = f"{BASE}/{path}?" + urllib.parse.urlencode(params)
    try:
        with urllib.request.urlopen(url, timeout=20) as r:
            return r.read().decode()
    except urllib.error.HTTPError as e:
        sys.exit(f"{path}: HTTP {e.code} — {e.read().decode()[:200]}")


def c_header(path, varname, raw, source):
    lines = []
    for i in range(0, len(raw), 200):
        chunk = raw[i:i + 200].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{chunk}"')
    return (
        "/* AUTO-GENERATED by tools/gen_owm_fixture.py — do not hand-edit.\n"
        f" * Source: {source}\n"
        f" * Captured: {__import__('datetime').date.today().isoformat()} */\n"
        "#pragma once\n\n"
        f"static const char {varname}[] =\n" + "\n".join(lines) + ";\n"
    )


def local_days(doc):
    """Group the 3-hour list into local calendar days, matching owm.c exactly."""
    tz = doc["city"]["timezone"]
    days = []
    for e in doc["list"]:
        d = (e["dt"] + tz) // 86400
        if not days or days[-1] != d:
            days.append(d)
    out = []
    for d in days:
        blocks = [e["main"] for e in doc["list"] if (e["dt"] + tz) // 86400 == d]
        out.append((min(b["temp_min"] for b in blocks),
                    max(b["temp_max"] for b in blocks),
                    len(blocks)))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lat", default="41.1")
    ap.add_argument("--lon", default="-112.0")
    a = ap.parse_args()
    key = read_key()
    common = {"lat": a.lat, "lon": a.lon, "units": "imperial", "appid": key}

    weather = fetch("weather", common)
    forecast = fetch("forecast", common)
    os.makedirs(OUT, exist_ok=True)
    open(os.path.join(OUT, "fixture_owm_weather25.h"), "w").write(
        c_header("weather", "OWM_WEATHER25_REAL", weather, f"GET {BASE}/weather lat={a.lat} lon={a.lon}"))
    open(os.path.join(OUT, "fixture_owm_forecast25.h"), "w").write(
        c_header("forecast", "OWM_FORECAST25_REAL", forecast, f"GET {BASE}/forecast lat={a.lat} lon={a.lon}"))

    # The expectations are emitted alongside the fixtures. They must NOT be hardcoded in
    # the test: the current-temperature reading changes every fetch, so a regenerated
    # fixture would silently desync from a pinned constant. The forecast blocks are
    # deterministic (fixed 3-hour grid), but the current reading is not.
    w = json.loads(weather)
    days = local_days(json.loads(forecast))
    exp = [
        "/* AUTO-GENERATED by tools/gen_owm_fixture.py — do not hand-edit. */",
        "#pragma once",
        "",
        "/* Independently computed from the captured JSON, not by the parser under test:",
        " * the 3-hour list is grouped by (dt + tz) / 86400 and temp_min/temp_max reduced",
        " * per local day. */",
        f"#define OWM_REAL_CURRENT_TEMP  ({w['main']['temp']})",
        f"#define OWM_REAL_CURRENT_DT    ({w['dt']}L)",
        f"#define OWM_REAL_NDAYS         ({len(days)})",
        "",
        "static const double OWM_REAL_EXP_MIN[] = { " +
        ", ".join(f"{lo}" for lo, _, _ in days) + " };",
        "static const double OWM_REAL_EXP_MAX[] = { " +
        ", ".join(f"{hi}" for _, hi, _ in days) + " };",
        "",
    ]
    open(os.path.join(OUT, "fixture_owm_expected.h"), "w").write("\n".join(exp))

    print(f"current temp: {w['main']['temp']} degF   dt={w['dt']}")
    print(f"{len(json.loads(forecast)['list'])} forecast blocks; local days:")
    for i, (lo, hi, n) in enumerate(days):
        print(f"  day {i}: n={n} min={lo} max={hi}")


if __name__ == "__main__":
    main()
