#!/usr/bin/env python3
"""Generate an ignored header holding bench-verification credentials.

Reads code/.env (gitignored, FR-30) and writes firmware/src/secrets_build.h, which is
ALSO gitignored. Nothing here is committed and nothing is baked into a tracked file: the
generated header is regenerated per machine, so a fresh clone simply has no credentials
until you run this.

The header is only for the bench verification build. Production credentials reach the
device through provisioning into NVS (FR-30), never through the firmware image.

Usage:
    python3 tools/gen_secrets_header.py            # write the header
    python3 tools/gen_secrets_header.py --remove   # delete it
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ENV_PATH = os.path.join(ROOT, ".env")
OUT_PATH = os.path.join(ROOT, "firmware", "src", "secrets_build.h")


def parse_env(path):
    values = {}
    if not os.path.exists(path):
        return values
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            key, val = key.strip(), val.strip()
            if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
                val = val[1:-1]
            values[key] = val
    return values


def c_string(s):
    """Escape for a C string literal. A quote or backslash in a password would otherwise
    break the header — or worse, inject code into it."""
    out = []
    for ch in s:
        if ch in '"\\':
            out.append("\\" + ch)
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            out.append("\\%03o" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--remove", action="store_true", help="delete the generated header")
    args = ap.parse_args()

    if args.remove:
        if os.path.exists(OUT_PATH):
            os.remove(OUT_PATH)
            print(f"removed {OUT_PATH}")
        else:
            print("nothing to remove")
        return 0

    env = parse_env(ENV_PATH)
    ssid = env.get("WIFI_SSID", "")
    password = env.get("WIFI_PASSWORD", "")
    owm = env.get("OWM_API_KEY", "")
    lat = env.get("LOCATION_LAT", "41.0")
    lon = env.get("LOCATION_LON", "-112.0")

    if not ssid:
        print("WIFI_SSID is not set in code/.env — cannot build the verification image",
              file=sys.stderr)
        return 1
    if not owm:
        print("OWM_API_KEY is not set in code/.env — cannot build the verification image",
              file=sys.stderr)
        return 1

    # The API key goes in a URL query string; anything outside this set would need
    # percent-encoding, so reject it rather than emit a URL that fails with a confusing 401.
    if not all(c.isalnum() or c in "-_" for c in owm):
        print("OWM_API_KEY contains characters needing URL encoding; refusing", file=sys.stderr)
        return 1

    url = (f"https://api.openweathermap.org/data/2.5/weather"
           f"?lat={lat}&lon={lon}&appid={owm}")

    body = f"""// GENERATED by tools/gen_secrets_header.py — DO NOT COMMIT, DO NOT EDIT.
// This file is gitignored. It exists only for the bench verification build (Task 11).
// Production credentials reach the device via provisioning into NVS (FR-30).
#pragma once
#define NET_VERIFY_SSID    {c_string(ssid)}
#define NET_VERIFY_PASS    {c_string(password)}
#define NET_VERIFY_OWM_URL {c_string(url)}
"""
    with open(OUT_PATH, "w") as fh:
        fh.write(body)
    os.chmod(OUT_PATH, 0o600)
    print(f"wrote {OUT_PATH} (mode 0600)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
