/* AUTO-GENERATED by tools/gen_owm_fixture.py — do not hand-edit. */
#pragma once

/* Independently computed from the captured JSON, not by the parser under test:
 * the 3-hour list is grouped by (dt + tz) / 86400 and temp_min/temp_max reduced
 * per local day. */
#define OWM_REAL_CURRENT_TEMP  (56.21)
#define OWM_REAL_CURRENT_DT    (1789796393L)
#define OWM_REAL_NDAYS         (5)

static const double OWM_REAL_EXP_MIN[] = { 54.18, 53.76, 43.07, 51.3, 50.38 };
static const double OWM_REAL_EXP_MAX[] = { 67.57, 68.11, 75.27, 76.21, 74.01 };
