/* AUTO-GENERATED by tools/gen_owm_fixture.py — do not hand-edit.
 * Source: GET https://api.openweathermap.org/data/2.5/weather lat=41.1 lon=-112.0
 * Captured: 2026-09-18 */
#pragma once

static const char OWM_WEATHER25_REAL[] =
    "{\"coord\":{\"lon\":-112,\"lat\":41.1},\"weather\":[{\"id\":801,\"main\":\"Clouds\",\"description\":\"few clouds\",\"icon\":\"02n\"}],\"base\":\"stations\",\"main\":{\"temp\":56.21,\"feels_like\":55.29,\"temp_min\":53.71,\"temp_max\":60"
    ".08,\"pressure\":1018,\"humidity\":80,\"sea_level\":1018,\"grnd_level\":864},\"visibility\":10000,\"wind\":{\"speed\":1.99,\"deg\":281,\"gust\":3},\"clouds\":{\"all\":24},\"dt\":1789796393,\"sys\":{\"type\":2,\"id\":2010220,\"count"
    "ry\":\"US\",\"sunrise\":1789737094,\"sunset\":1789781569},\"timezone\":-21600,\"id\":5775931,\"name\":\"Hillside Estates\",\"cod\":200}";
